import {SelectItem} from 'primeng/api';

export const ASSET_PATH = 'asset_path';
export const CONDITION_API_PATH = 'condition_api_path';
export const DOCUMENT_API_PATH = 'document_api_path';
export const EXTENSION_API_PATH = 'extension_api_path';
export const FIELD_DEFINITION_API_PATH = 'field_definition_api_path';
export const LINKS_API_PATH = 'links_api_path';
export const METADATA_API_PATH = 'metadata_api_path';
export const DATA_LIST_API_PATH = 'data_list_api_path';
export const PUBLIC_DATA_API_PATH = 'public_data_api_path';
export const SELECT_QUERY_API_PATH = 'select_query_api_path';
export const USER_API_PATH = 'user_api_path';
export const ROLE_API_PATH = 'role_api_path';
export const USER_ROLES_API_PATH = 'user_roles_api_path';
export const URL_MAP_RULES_API_PATH = 'url_map_rules_api_path';
export const API_SERVICE_PATH = 'api_service_path';
export const LOGIN_API_PATH = 'login_api_path';
export const CHANGEPASSWORD_API_PATH = 'changepassword_api_path';
export const APP_VERSION = '1.0.RC4';

export const CONFIG_PATH = '/assets/config.json';

export const DROPPABLE_API_PATH = 'droppable_api_path';
export const DRAGGABLE_API_PATH = 'draggable_api_path';
// se FS => /files/
// se S3 => /files/

// export const BASE_PATH = 'https://s3.eu-central-1.amazonaws.com/portale-si/';
export const BASE_PATH = '/files/';
export const TOKEN_ITEM = 'snello-token';
export const REFRESH_TOKEN_ITEM = 'snello-refresh-token';
export const USER_ITEM = 'snello-user';
export const CONTENT_TYPE = 'Content-Type';
export const APPLICATION_JSON = 'application/json';
export const AUTHORIZATION = 'Authorization';
export const BEARER_ = 'Bearer ';

export const ADMIN_ITEMS: any[] = [
    {
        id: 'list',
        icon: 'fa fa-book',
        section: 'metadata',
        name: 'Metadati',
        summary: 'Gestione dei metadati sulle tabelle',
        roles: 'metadatas_edit, metadatas_view'
    },
    {
        id: 'list',
        icon: 'fa fa-cogs',
        section: 'fielddefinition',
        name: 'Field Definitions',
        summary: 'Gestione definizione dei campi per popolare le form',
        roles: 'fielddefinitions_edit, fielddefinitions_view'
    },
    {
        id: 'list',
        icon: 'fa fa-hand-spock-o',
        section: 'condition',
        name: 'Condition',
        summary: 'Gestione delle condizioni di filtro delle tabelle',
        roles: 'conditions_edit, conditions_view'
    },
    {
        id: 'list',
        icon: 'fa fa-files-o',
        section: 'document',
        name: 'Document',
        summary: 'Gestione dei documenti',
        roles: 'documents_edit, documents_view'
    },
    {
        id: 'edit',
        icon: 'fa fa-globe',
        section: 'publicdata',
        name: 'Public Data',
        summary: 'Upload di dati',
        roles: 'publicdata_edit'
    },
    {
        id: 'list',
        icon: 'fa fa-list',
        section: 'selectqueries',
        name: 'SelectQuery',
        summary: 'Query di selezione',
        roles: 'selectqueries_edit, selectqueries_view'
    },
    {
        id: 'list',
        icon: 'fa fa-user-circle-o',
        section: 'user',
        name: 'User',
        summary: 'Users',
        roles: 'users_edit, users_view'
    },
    {
        id: 'list',
        icon: 'fa fa-address-card-o',
        section: 'role',
        name: 'Role',
        summary: 'Roles',
        roles: 'roles_edit,roles_view'
    },
    {
        id: 'list',
        icon: 'fa fa-map-signs',
        section: 'urlmaprules',
        name: 'Url Map Rules',
        summary: 'Url Map Rules',
        roles: 'urlmaprules_edit, urlmaprules_view'
    },
    {
        id: 'list',
        icon: 'fa fa-link',
        section: 'links',
        name: 'Links',
        summary: 'Links',
        roles: 'links_edit, links_view'
    },
    {
        id: 'list',
        icon: 'fa fa-puzzle-piece',
        section: 'draggables',
        name: 'Draggables',
        summary: 'Draggables',
        roles: 'draggables_edit, draggables_view'
    },
    {
        id: 'list',
        icon: 'fa fa-shopping-basket',
        section: 'droppables',
        name: 'Droppables',
        summary: 'Droppables',
        roles: 'droppables_edit, droppables_view'
    }
];

export const FONT_AWESOME_ICONS: SelectItem[] = [
    {label: 'fa glass', value: 'fa fa-glass'},
    {label: 'fa music', value: 'fa fa-music'},
    {label: 'fa search', value: 'fa fa-search'},
    {label: 'fa envelope o', value: 'fa fa-envelope-o'},
    {label: 'fa heart', value: 'fa fa-heart'},
    {label: 'fa star', value: 'fa fa-star'},
    {label: 'fa star o', value: 'fa fa-star-o'},
    {label: 'fa user', value: 'fa fa-user'},
    {label: 'fa film', value: 'fa fa-film'},
    {label: 'fa th large', value: 'fa fa-th-large'},
    {label: 'fa th', value: 'fa fa-th'},
    {label: 'fa th list', value: 'fa fa-th-list'},
    {label: 'fa check', value: 'fa fa-check'},
    {label: 'fa times', value: 'fa fa-times'},
    {label: 'fa search plus', value: 'fa fa-search-plus'},
    {label: 'fa search minus', value: 'fa fa-search-minus'},
    {label: 'fa power off', value: 'fa fa-power-off'},
    {label: 'fa signal', value: 'fa fa-signal'},
    {label: 'fa cog', value: 'fa fa-cog'},
    {label: 'fa trash o', value: 'fa fa-trash-o'},
    {label: 'fa home', value: 'fa fa-home'},
    {label: 'fa file o', value: 'fa fa-file-o'},
    {label: 'fa clock o', value: 'fa fa-clock-o'},
    {label: 'fa road', value: 'fa fa-road'},
    {label: 'fa download', value: 'fa fa-download'},
    {label: 'fa arrow circle o down', value: 'fa fa-arrow-circle-o-down'},
    {label: 'fa arrow circle o up', value: 'fa fa-arrow-circle-o-up'},
    {label: 'fa inbox', value: 'fa fa-inbox'},
    {label: 'fa play circle o', value: 'fa fa-play-circle-o'},
    {label: 'fa repeat', value: 'fa fa-repeat'},
    {label: 'fa refresh', value: 'fa fa-refresh'},
    {label: 'fa list alt', value: 'fa fa-list-alt'},
    {label: 'fa lock', value: 'fa fa-lock'},
    {label: 'fa flag', value: 'fa fa-flag'},
    {label: 'fa headphones', value: 'fa fa-headphones'},
    {label: 'fa volume off', value: 'fa fa-volume-off'},
    {label: 'fa volume down', value: 'fa fa-volume-down'},
    {label: 'fa volume up', value: 'fa fa-volume-up'},
    {label: 'fa qrcode', value: 'fa fa-qrcode'},
    {label: 'fa barcode', value: 'fa fa-barcode'},
    {label: 'fa tag', value: 'fa fa-tag'},
    {label: 'fa tags', value: 'fa fa-tags'},
    {label: 'fa book', value: 'fa fa-book'},
    {label: 'fa bookmark', value: 'fa fa-bookmark'},
    {label: 'fa print', value: 'fa fa-print'},
    {label: 'fa camera', value: 'fa fa-camera'},
    {label: 'fa font', value: 'fa fa-font'},
    {label: 'fa bold', value: 'fa fa-bold'},
    {label: 'fa italic', value: 'fa fa-italic'},
    {label: 'fa text height', value: 'fa fa-text-height'},
    {label: 'fa text width', value: 'fa fa-text-width'},
    {label: 'fa align left', value: 'fa fa-align-left'},
    {label: 'fa align center', value: 'fa fa-align-center'},
    {label: 'fa align right', value: 'fa fa-align-right'},
    {label: 'fa align justify', value: 'fa fa-align-justify'},
    {label: 'fa list', value: 'fa fa-list'},
    {label: 'fa outdent', value: 'fa fa-outdent'},
    {label: 'fa indent', value: 'fa fa-indent'},
    {label: 'fa video camera', value: 'fa fa-video-camera'},
    {label: 'fa picture o', value: 'fa fa-picture-o'},
    {label: 'fa pencil', value: 'fa fa-pencil'},
    {label: 'fa map marker', value: 'fa fa-map-marker'},
    {label: 'fa adjust', value: 'fa fa-adjust'},
    {label: 'fa tint', value: 'fa fa-tint'},
    {label: 'fa pencil square o', value: 'fa fa-pencil-square-o'},
    {label: 'fa share square o', value: 'fa fa-share-square-o'},
    {label: 'fa check square o', value: 'fa fa-check-square-o'},
    {label: 'fa arrows', value: 'fa fa-arrows'},
    {label: 'fa step backward', value: 'fa fa-step-backward'},
    {label: 'fa fast backward', value: 'fa fa-fast-backward'},
    {label: 'fa backward', value: 'fa fa-backward'},
    {label: 'fa play', value: 'fa fa-play'},
    {label: 'fa pause', value: 'fa fa-pause'},
    {label: 'fa stop', value: 'fa fa-stop'},
    {label: 'fa forward', value: 'fa fa-forward'},
    {label: 'fa fast forward', value: 'fa fa-fast-forward'},
    {label: 'fa step forward', value: 'fa fa-step-forward'},
    {label: 'fa eject', value: 'fa fa-eject'},
    {label: 'fa chevron left', value: 'fa fa-chevron-left'},
    {label: 'fa chevron right', value: 'fa fa-chevron-right'},
    {label: 'fa plus circle', value: 'fa fa-plus-circle'},
    {label: 'fa minus circle', value: 'fa fa-minus-circle'},
    {label: 'fa times circle', value: 'fa fa-times-circle'},
    {label: 'fa check circle', value: 'fa fa-check-circle'},
    {label: 'fa question circle', value: 'fa fa-question-circle'},
    {label: 'fa info circle', value: 'fa fa-info-circle'},
    {label: 'fa crosshairs', value: 'fa fa-crosshairs'},
    {label: 'fa times circle o', value: 'fa fa-times-circle-o'},
    {label: 'fa check circle o', value: 'fa fa-check-circle-o'},
    {label: 'fa ban', value: 'fa fa-ban'},
    {label: 'fa arrow left', value: 'fa fa-arrow-left'},
    {label: 'fa arrow right', value: 'fa fa-arrow-right'},
    {label: 'fa arrow up', value: 'fa fa-arrow-up'},
    {label: 'fa arrow down', value: 'fa fa-arrow-down'},
    {label: 'fa share', value: 'fa fa-share'},
    {label: 'fa expand', value: 'fa fa-expand'},
    {label: 'fa compress', value: 'fa fa-compress'},
    {label: 'fa plus', value: 'fa fa-plus'},
    {label: 'fa minus', value: 'fa fa-minus'},
    {label: 'fa asterisk', value: 'fa fa-asterisk'},
    {label: 'fa exclamation circle', value: 'fa fa-exclamation-circle'},
    {label: 'fa gift', value: 'fa fa-gift'},
    {label: 'fa leaf', value: 'fa fa-leaf'},
    {label: 'fa fire', value: 'fa fa-fire'},
    {label: 'fa eye', value: 'fa fa-eye'},
    {label: 'fa eye slash', value: 'fa fa-eye-slash'},
    {label: 'fa exclamation triangle', value: 'fa fa-exclamation-triangle'},
    {label: 'fa plane', value: 'fa fa-plane'},
    {label: 'fa calendar', value: 'fa fa-calendar'},
    {label: 'fa random', value: 'fa fa-random'},
    {label: 'fa comment', value: 'fa fa-comment'},
    {label: 'fa magnet', value: 'fa fa-magnet'},
    {label: 'fa chevron up', value: 'fa fa-chevron-up'},
    {label: 'fa chevron down', value: 'fa fa-chevron-down'},
    {label: 'fa retweet', value: 'fa fa-retweet'},
    {label: 'fa shopping cart', value: 'fa fa-shopping-cart'},
    {label: 'fa folder', value: 'fa fa-folder'},
    {label: 'fa folder open', value: 'fa fa-folder-open'},
    {label: 'fa arrows v', value: 'fa fa-arrows-v'},
    {label: 'fa arrows h', value: 'fa fa-arrows-h'},
    {label: 'fa bar chart', value: 'fa fa-bar-chart'},
    {label: 'fa twitter square', value: 'fa fa-twitter-square'},
    {label: 'fa facebook square', value: 'fa fa-facebook-square'},
    {label: 'fa camera retro', value: 'fa fa-camera-retro'},
    {label: 'fa key', value: 'fa fa-key'},
    {label: 'fa cogs', value: 'fa fa-cogs'},
    {label: 'fa comments', value: 'fa fa-comments'},
    {label: 'fa thumbs o up', value: 'fa fa-thumbs-o-up'},
    {label: 'fa thumbs o down', value: 'fa fa-thumbs-o-down'},
    {label: 'fa star half', value: 'fa fa-star-half'},
    {label: 'fa heart o', value: 'fa fa-heart-o'},
    {label: 'fa sign out', value: 'fa fa-sign-out'},
    {label: 'fa linkedin square', value: 'fa fa-linkedin-square'},
    {label: 'fa thumb tack', value: 'fa fa-thumb-tack'},
    {label: 'fa external link', value: 'fa fa-external-link'},
    {label: 'fa sign in', value: 'fa fa-sign-in'},
    {label: 'fa trophy', value: 'fa fa-trophy'},
    {label: 'fa github square', value: 'fa fa-github-square'},
    {label: 'fa upload', value: 'fa fa-upload'},
    {label: 'fa lemon o', value: 'fa fa-lemon-o'},
    {label: 'fa phone', value: 'fa fa-phone'},
    {label: 'fa square o', value: 'fa fa-square-o'},
    {label: 'fa bookmark o', value: 'fa fa-bookmark-o'},
    {label: 'fa phone square', value: 'fa fa-phone-square'},
    {label: 'fa twitter', value: 'fa fa-twitter'},
    {label: 'fa facebook', value: 'fa fa-facebook'},
    {label: 'fa github', value: 'fa fa-github'},
    {label: 'fa unlock', value: 'fa fa-unlock'},
    {label: 'fa credit card', value: 'fa fa-credit-card'},
    {label: 'fa rss', value: 'fa fa-rss'},
    {label: 'fa hdd o', value: 'fa fa-hdd-o'},
    {label: 'fa bullhorn', value: 'fa fa-bullhorn'},
    {label: 'fa bell', value: 'fa fa-bell'},
    {label: 'fa certificate', value: 'fa fa-certificate'},
    {label: 'fa hand o right', value: 'fa fa-hand-o-right'},
    {label: 'fa hand o left', value: 'fa fa-hand-o-left'},
    {label: 'fa hand o up', value: 'fa fa-hand-o-up'},
    {label: 'fa hand o down', value: 'fa fa-hand-o-down'},
    {label: 'fa arrow circle left', value: 'fa fa-arrow-circle-left'},
    {label: 'fa arrow circle right', value: 'fa fa-arrow-circle-right'},
    {label: 'fa arrow circle up', value: 'fa fa-arrow-circle-up'},
    {label: 'fa arrow circle down', value: 'fa fa-arrow-circle-down'},
    {label: 'fa globe', value: 'fa fa-globe'},
    {label: 'fa wrench', value: 'fa fa-wrench'},
    {label: 'fa tasks', value: 'fa fa-tasks'},
    {label: 'fa filter', value: 'fa fa-filter'},
    {label: 'fa briefcase', value: 'fa fa-briefcase'},
    {label: 'fa arrows alt', value: 'fa fa-arrows-alt'},
    {label: 'fa users', value: 'fa fa-users'},
    {label: 'fa link', value: 'fa fa-link'},
    {label: 'fa cloud', value: 'fa fa-cloud'},
    {label: 'fa flask', value: 'fa fa-flask'},
    {label: 'fa scissors', value: 'fa fa-scissors'},
    {label: 'fa files o', value: 'fa fa-files-o'},
    {label: 'fa paperclip', value: 'fa fa-paperclip'},
    {label: 'fa floppy o', value: 'fa fa-floppy-o'},
    {label: 'fa square', value: 'fa fa-square'},
    {label: 'fa bars', value: 'fa fa-bars'},
    {label: 'fa list ul', value: 'fa fa-list-ul'},
    {label: 'fa list ol', value: 'fa fa-list-ol'},
    {label: 'fa strikethrough', value: 'fa fa-strikethrough'},
    {label: 'fa underline', value: 'fa fa-underline'},
    {label: 'fa table', value: 'fa fa-table'},
    {label: 'fa magic', value: 'fa fa-magic'},
    {label: 'fa truck', value: 'fa fa-truck'},
    {label: 'fa pinterest', value: 'fa fa-pinterest'},
    {label: 'fa pinterest square', value: 'fa fa-pinterest-square'},
    {label: 'fa google plus square', value: 'fa fa-google-plus-square'},
    {label: 'fa google plus', value: 'fa fa-google-plus'},
    {label: 'fa money', value: 'fa fa-money'},
    {label: 'fa caret down', value: 'fa fa-caret-down'},
    {label: 'fa caret up', value: 'fa fa-caret-up'},
    {label: 'fa caret left', value: 'fa fa-caret-left'},
    {label: 'fa caret right', value: 'fa fa-caret-right'},
    {label: 'fa columns', value: 'fa fa-columns'},
    {label: 'fa sort', value: 'fa fa-sort'},
    {label: 'fa sort desc', value: 'fa fa-sort-desc'},
    {label: 'fa sort asc', value: 'fa fa-sort-asc'},
    {label: 'fa envelope', value: 'fa fa-envelope'},
    {label: 'fa linkedin', value: 'fa fa-linkedin'},
    {label: 'fa undo', value: 'fa fa-undo'},
    {label: 'fa gavel', value: 'fa fa-gavel'},
    {label: 'fa tachometer', value: 'fa fa-tachometer'},
    {label: 'fa comment o', value: 'fa fa-comment-o'},
    {label: 'fa comments o', value: 'fa fa-comments-o'},
    {label: 'fa bolt', value: 'fa fa-bolt'},
    {label: 'fa sitemap', value: 'fa fa-sitemap'},
    {label: 'fa umbrella', value: 'fa fa-umbrella'},
    {label: 'fa clipboard', value: 'fa fa-clipboard'},
    {label: 'fa lightbulb o', value: 'fa fa-lightbulb-o'},
    {label: 'fa exchange', value: 'fa fa-exchange'},
    {label: 'fa cloud download', value: 'fa fa-cloud-download'},
    {label: 'fa cloud upload', value: 'fa fa-cloud-upload'},
    {label: 'fa user md', value: 'fa fa-user-md'},
    {label: 'fa stethoscope', value: 'fa fa-stethoscope'},
    {label: 'fa suitcase', value: 'fa fa-suitcase'},
    {label: 'fa bell o', value: 'fa fa-bell-o'},
    {label: 'fa coffee', value: 'fa fa-coffee'},
    {label: 'fa cutlery', value: 'fa fa-cutlery'},
    {label: 'fa file text o', value: 'fa fa-file-text-o'},
    {label: 'fa building o', value: 'fa fa-building-o'},
    {label: 'fa hospital o', value: 'fa fa-hospital-o'},
    {label: 'fa ambulance', value: 'fa fa-ambulance'},
    {label: 'fa medkit', value: 'fa fa-medkit'},
    {label: 'fa fighter jet', value: 'fa fa-fighter-jet'},
    {label: 'fa beer', value: 'fa fa-beer'},
    {label: 'fa h square', value: 'fa fa-h-square'},
    {label: 'fa plus square', value: 'fa fa-plus-square'},
    {label: 'fa angle double left', value: 'fa fa-angle-double-left'},
    {label: 'fa angle double right', value: 'fa fa-angle-double-right'},
    {label: 'fa angle double up', value: 'fa fa-angle-double-up'},
    {label: 'fa angle double down', value: 'fa fa-angle-double-down'},
    {label: 'fa angle left', value: 'fa fa-angle-left'},
    {label: 'fa angle right', value: 'fa fa-angle-right'},
    {label: 'fa angle up', value: 'fa fa-angle-up'},
    {label: 'fa angle down', value: 'fa fa-angle-down'},
    {label: 'fa desktop', value: 'fa fa-desktop'},
    {label: 'fa laptop', value: 'fa fa-laptop'},
    {label: 'fa tablet', value: 'fa fa-tablet'},
    {label: 'fa mobile', value: 'fa fa-mobile'},
    {label: 'fa circle o', value: 'fa fa-circle-o'},
    {label: 'fa quote left', value: 'fa fa-quote-left'},
    {label: 'fa quote right', value: 'fa fa-quote-right'},
    {label: 'fa spinner', value: 'fa fa-spinner'},
    {label: 'fa circle', value: 'fa fa-circle'},
    {label: 'fa reply', value: 'fa fa-reply'},
    {label: 'fa github alt', value: 'fa fa-github-alt'},
    {label: 'fa folder o', value: 'fa fa-folder-o'},
    {label: 'fa folder open o', value: 'fa fa-folder-open-o'},
    {label: 'fa smile o', value: 'fa fa-smile-o'},
    {label: 'fa frown o', value: 'fa fa-frown-o'},
    {label: 'fa meh o', value: 'fa fa-meh-o'},
    {label: 'fa gamepad', value: 'fa fa-gamepad'},
    {label: 'fa keyboard o', value: 'fa fa-keyboard-o'},
    {label: 'fa flag o', value: 'fa fa-flag-o'},
    {label: 'fa flag checkered', value: 'fa fa-flag-checkered'},
    {label: 'fa terminal', value: 'fa fa-terminal'},
    {label: 'fa code', value: 'fa fa-code'},
    {label: 'fa reply all', value: 'fa fa-reply-all'},
    {label: 'fa star half o', value: 'fa fa-star-half-o'},
    {label: 'fa location arrow', value: 'fa fa-location-arrow'},
    {label: 'fa crop', value: 'fa fa-crop'},
    {label: 'fa code fork', value: 'fa fa-code-fork'},
    {label: 'fa chain broken', value: 'fa fa-chain-broken'},
    {label: 'fa question', value: 'fa fa-question'},
    {label: 'fa info', value: 'fa fa-info'},
    {label: 'fa exclamation', value: 'fa fa-exclamation'},
    {label: 'fa superscript', value: 'fa fa-superscript'},
    {label: 'fa subscript', value: 'fa fa-subscript'},
    {label: 'fa eraser', value: 'fa fa-eraser'},
    {label: 'fa puzzle piece', value: 'fa fa-puzzle-piece'},
    {label: 'fa microphone', value: 'fa fa-microphone'},
    {label: 'fa microphone slash', value: 'fa fa-microphone-slash'},
    {label: 'fa shield', value: 'fa fa-shield'},
    {label: 'fa calendar o', value: 'fa fa-calendar-o'},
    {label: 'fa fire extinguisher', value: 'fa fa-fire-extinguisher'},
    {label: 'fa rocket', value: 'fa fa-rocket'},
    {label: 'fa maxcdn', value: 'fa fa-maxcdn'},
    {label: 'fa chevron circle left', value: 'fa fa-chevron-circle-left'},
    {label: 'fa chevron circle right', value: 'fa fa-chevron-circle-right'},
    {label: 'fa chevron circle up', value: 'fa fa-chevron-circle-up'},
    {label: 'fa chevron circle down', value: 'fa fa-chevron-circle-down'},
    {label: 'fa html5', value: 'fa fa-html5'},
    {label: 'fa css3', value: 'fa fa-css3'},
    {label: 'fa anchor', value: 'fa fa-anchor'},
    {label: 'fa unlock alt', value: 'fa fa-unlock-alt'},
    {label: 'fa bullseye', value: 'fa fa-bullseye'},
    {label: 'fa ellipsis h', value: 'fa fa-ellipsis-h'},
    {label: 'fa ellipsis v', value: 'fa fa-ellipsis-v'},
    {label: 'fa rss square', value: 'fa fa-rss-square'},
    {label: 'fa play circle', value: 'fa fa-play-circle'},
    {label: 'fa ticket', value: 'fa fa-ticket'},
    {label: 'fa minus square', value: 'fa fa-minus-square'},
    {label: 'fa minus square o', value: 'fa fa-minus-square-o'},
    {label: 'fa level up', value: 'fa fa-level-up'},
    {label: 'fa level down', value: 'fa fa-level-down'},
    {label: 'fa check square', value: 'fa fa-check-square'},
    {label: 'fa pencil square', value: 'fa fa-pencil-square'},
    {label: 'fa external link square', value: 'fa fa-external-link-square'},
    {label: 'fa share square', value: 'fa fa-share-square'},
    {label: 'fa compass', value: 'fa fa-compass'},
    {label: 'fa caret square o down', value: 'fa fa-caret-square-o-down'},
    {label: 'fa caret square o up', value: 'fa fa-caret-square-o-up'},
    {label: 'fa caret square o right', value: 'fa fa-caret-square-o-right'},
    {label: 'fa eur', value: 'fa fa-eur'},
    {label: 'fa gbp', value: 'fa fa-gbp'},
    {label: 'fa usd', value: 'fa fa-usd'},
    {label: 'fa inr', value: 'fa fa-inr'},
    {label: 'fa jpy', value: 'fa fa-jpy'},
    {label: 'fa rub', value: 'fa fa-rub'},
    {label: 'fa krw', value: 'fa fa-krw'},
    {label: 'fa btc', value: 'fa fa-btc'},
    {label: 'fa file', value: 'fa fa-file'},
    {label: 'fa file text', value: 'fa fa-file-text'},
    {label: 'fa sort alpha asc', value: 'fa fa-sort-alpha-asc'},
    {label: 'fa sort alpha desc', value: 'fa fa-sort-alpha-desc'},
    {label: 'fa sort amount asc', value: 'fa fa-sort-amount-asc'},
    {label: 'fa sort amount desc', value: 'fa fa-sort-amount-desc'},
    {label: 'fa sort numeric asc', value: 'fa fa-sort-numeric-asc'},
    {label: 'fa sort numeric desc', value: 'fa fa-sort-numeric-desc'},
    {label: 'fa thumbs up', value: 'fa fa-thumbs-up'},
    {label: 'fa thumbs down', value: 'fa fa-thumbs-down'},
    {label: 'fa youtube square', value: 'fa fa-youtube-square'},
    {label: 'fa youtube', value: 'fa fa-youtube'},
    {label: 'fa xing', value: 'fa fa-xing'},
    {label: 'fa xing square', value: 'fa fa-xing-square'},
    {label: 'fa youtube play', value: 'fa fa-youtube-play'},
    {label: 'fa dropbox', value: 'fa fa-dropbox'},
    {label: 'fa stack overflow', value: 'fa fa-stack-overflow'},
    {label: 'fa instagram', value: 'fa fa-instagram'},
    {label: 'fa flickr', value: 'fa fa-flickr'},
    {label: 'fa adn', value: 'fa fa-adn'},
    {label: 'fa bitbucket', value: 'fa fa-bitbucket'},
    {label: 'fa bitbucket square', value: 'fa fa-bitbucket-square'},
    {label: 'fa tumblr', value: 'fa fa-tumblr'},
    {label: 'fa tumblr square', value: 'fa fa-tumblr-square'},
    {label: 'fa long arrow down', value: 'fa fa-long-arrow-down'},
    {label: 'fa long arrow up', value: 'fa fa-long-arrow-up'},
    {label: 'fa long arrow left', value: 'fa fa-long-arrow-left'},
    {label: 'fa long arrow right', value: 'fa fa-long-arrow-right'},
    {label: 'fa apple', value: 'fa fa-apple'},
    {label: 'fa windows', value: 'fa fa-windows'},
    {label: 'fa android', value: 'fa fa-android'},
    {label: 'fa linux', value: 'fa fa-linux'},
    {label: 'fa dribbble', value: 'fa fa-dribbble'},
    {label: 'fa skype', value: 'fa fa-skype'},
    {label: 'fa foursquare', value: 'fa fa-foursquare'},
    {label: 'fa trello', value: 'fa fa-trello'},
    {label: 'fa female', value: 'fa fa-female'},
    {label: 'fa male', value: 'fa fa-male'},
    {label: 'fa gratipay', value: 'fa fa-gratipay'},
    {label: 'fa sun o', value: 'fa fa-sun-o'},
    {label: 'fa moon o', value: 'fa fa-moon-o'},
    {label: 'fa archive', value: 'fa fa-archive'},
    {label: 'fa bug', value: 'fa fa-bug'},
    {label: 'fa vk', value: 'fa fa-vk'},
    {label: 'fa weibo', value: 'fa fa-weibo'},
    {label: 'fa renren', value: 'fa fa-renren'},
    {label: 'fa pagelines', value: 'fa fa-pagelines'},
    {label: 'fa stack exchange', value: 'fa fa-stack-exchange'},
    {label: 'fa arrow circle o right', value: 'fa fa-arrow-circle-o-right'},
    {label: 'fa arrow circle o left', value: 'fa fa-arrow-circle-o-left'},
    {label: 'fa caret square o left', value: 'fa fa-caret-square-o-left'},
    {label: 'fa dot circle o', value: 'fa fa-dot-circle-o'},
    {label: 'fa wheelchair', value: 'fa fa-wheelchair'},
    {label: 'fa vimeo square', value: 'fa fa-vimeo-square'},
    {label: 'fa try', value: 'fa fa-try'},
    {label: 'fa plus square o', value: 'fa fa-plus-square-o'},
    {label: 'fa space shuttle', value: 'fa fa-space-shuttle'},
    {label: 'fa slack', value: 'fa fa-slack'},
    {label: 'fa envelope square', value: 'fa fa-envelope-square'},
    {label: 'fa wordpress', value: 'fa fa-wordpress'},
    {label: 'fa openid', value: 'fa fa-openid'},
    {label: 'fa university', value: 'fa fa-university'},
    {label: 'fa graduation cap', value: 'fa fa-graduation-cap'},
    {label: 'fa yahoo', value: 'fa fa-yahoo'},
    {label: 'fa google', value: 'fa fa-google'},
    {label: 'fa reddit', value: 'fa fa-reddit'},
    {label: 'fa reddit square', value: 'fa fa-reddit-square'},
    {label: 'fa stumbleupon circle', value: 'fa fa-stumbleupon-circle'},
    {label: 'fa stumbleupon', value: 'fa fa-stumbleupon'},
    {label: 'fa delicious', value: 'fa fa-delicious'},
    {label: 'fa digg', value: 'fa fa-digg'},
    {label: 'fa pied piper pp', value: 'fa fa-pied-piper-pp'},
    {label: 'fa pied piper alt', value: 'fa fa-pied-piper-alt'},
    {label: 'fa drupal', value: 'fa fa-drupal'},
    {label: 'fa joomla', value: 'fa fa-joomla'},
    {label: 'fa language', value: 'fa fa-language'},
    {label: 'fa fax', value: 'fa fa-fax'},
    {label: 'fa building', value: 'fa fa-building'},
    {label: 'fa child', value: 'fa fa-child'},
    {label: 'fa paw', value: 'fa fa-paw'},
    {label: 'fa spoon', value: 'fa fa-spoon'},
    {label: 'fa cube', value: 'fa fa-cube'},
    {label: 'fa cubes', value: 'fa fa-cubes'},
    {label: 'fa behance', value: 'fa fa-behance'},
    {label: 'fa behance square', value: 'fa fa-behance-square'},
    {label: 'fa steam', value: 'fa fa-steam'},
    {label: 'fa steam square', value: 'fa fa-steam-square'},
    {label: 'fa recycle', value: 'fa fa-recycle'},
    {label: 'fa car', value: 'fa fa-car'},
    {label: 'fa taxi', value: 'fa fa-taxi'},
    {label: 'fa tree', value: 'fa fa-tree'},
    {label: 'fa spotify', value: 'fa fa-spotify'},
    {label: 'fa deviantart', value: 'fa fa-deviantart'},
    {label: 'fa soundcloud', value: 'fa fa-soundcloud'},
    {label: 'fa database', value: 'fa fa-database'},
    {label: 'fa file pdf o', value: 'fa fa-file-pdf-o'},
    {label: 'fa file word o', value: 'fa fa-file-word-o'},
    {label: 'fa file excel o', value: 'fa fa-file-excel-o'},
    {label: 'fa file powerpoint o', value: 'fa fa-file-powerpoint-o'},
    {label: 'fa file image o', value: 'fa fa-file-image-o'},
    {label: 'fa file archive o', value: 'fa fa-file-archive-o'},
    {label: 'fa file audio o', value: 'fa fa-file-audio-o'},
    {label: 'fa file video o', value: 'fa fa-file-video-o'},
    {label: 'fa file code o', value: 'fa fa-file-code-o'},
    {label: 'fa vine', value: 'fa fa-vine'},
    {label: 'fa codepen', value: 'fa fa-codepen'},
    {label: 'fa jsfiddle', value: 'fa fa-jsfiddle'},
    {label: 'fa life ring', value: 'fa fa-life-ring'},
    {label: 'fa circle o notch', value: 'fa fa-circle-o-notch'},
    {label: 'fa rebel', value: 'fa fa-rebel'},
    {label: 'fa empire', value: 'fa fa-empire'},
    {label: 'fa git square', value: 'fa fa-git-square'},
    {label: 'fa git', value: 'fa fa-git'},
    {label: 'fa hacker news', value: 'fa fa-hacker-news'},
    {label: 'fa tencent weibo', value: 'fa fa-tencent-weibo'},
    {label: 'fa qq', value: 'fa fa-qq'},
    {label: 'fa weixin', value: 'fa fa-weixin'},
    {label: 'fa paper plane', value: 'fa fa-paper-plane'},
    {label: 'fa paper plane o', value: 'fa fa-paper-plane-o'},
    {label: 'fa history', value: 'fa fa-history'},
    {label: 'fa circle thin', value: 'fa fa-circle-thin'},
    {label: 'fa header', value: 'fa fa-header'},
    {label: 'fa paragraph', value: 'fa fa-paragraph'},
    {label: 'fa sliders', value: 'fa fa-sliders'},
    {label: 'fa share alt', value: 'fa fa-share-alt'},
    {label: 'fa share alt square', value: 'fa fa-share-alt-square'},
    {label: 'fa bomb', value: 'fa fa-bomb'},
    {label: 'fa futbol o', value: 'fa fa-futbol-o'},
    {label: 'fa tty', value: 'fa fa-tty'},
    {label: 'fa binoculars', value: 'fa fa-binoculars'},
    {label: 'fa plug', value: 'fa fa-plug'},
    {label: 'fa slideshare', value: 'fa fa-slideshare'},
    {label: 'fa twitch', value: 'fa fa-twitch'},
    {label: 'fa yelp', value: 'fa fa-yelp'},
    {label: 'fa newspaper o', value: 'fa fa-newspaper-o'},
    {label: 'fa wifi', value: 'fa fa-wifi'},
    {label: 'fa calculator', value: 'fa fa-calculator'},
    {label: 'fa paypal', value: 'fa fa-paypal'},
    {label: 'fa google wallet', value: 'fa fa-google-wallet'},
    {label: 'fa cc visa', value: 'fa fa-cc-visa'},
    {label: 'fa cc mastercard', value: 'fa fa-cc-mastercard'},
    {label: 'fa cc discover', value: 'fa fa-cc-discover'},
    {label: 'fa cc amex', value: 'fa fa-cc-amex'},
    {label: 'fa cc paypal', value: 'fa fa-cc-paypal'},
    {label: 'fa cc stripe', value: 'fa fa-cc-stripe'},
    {label: 'fa bell slash', value: 'fa fa-bell-slash'},
    {label: 'fa bell slash o', value: 'fa fa-bell-slash-o'},
    {label: 'fa trash', value: 'fa fa-trash'},
    {label: 'fa copyright', value: 'fa fa-copyright'},
    {label: 'fa at', value: 'fa fa-at'},
    {label: 'fa eyedropper', value: 'fa fa-eyedropper'},
    {label: 'fa paint brush', value: 'fa fa-paint-brush'},
    {label: 'fa birthday cake', value: 'fa fa-birthday-cake'},
    {label: 'fa area chart', value: 'fa fa-area-chart'},
    {label: 'fa pie chart', value: 'fa fa-pie-chart'},
    {label: 'fa line chart', value: 'fa fa-line-chart'},
    {label: 'fa lastfm', value: 'fa fa-lastfm'},
    {label: 'fa lastfm square', value: 'fa fa-lastfm-square'},
    {label: 'fa toggle off', value: 'fa fa-toggle-off'},
    {label: 'fa toggle on', value: 'fa fa-toggle-on'},
    {label: 'fa bicycle', value: 'fa fa-bicycle'},
    {label: 'fa bus', value: 'fa fa-bus'},
    {label: 'fa ioxhost', value: 'fa fa-ioxhost'},
    {label: 'fa angellist', value: 'fa fa-angellist'},
    {label: 'fa cc', value: 'fa fa-cc'},
    {label: 'fa ils', value: 'fa fa-ils'},
    {label: 'fa meanpath', value: 'fa fa-meanpath'},
    {label: 'fa buysellads', value: 'fa fa-buysellads'},
    {label: 'fa connectdevelop', value: 'fa fa-connectdevelop'},
    {label: 'fa dashcube', value: 'fa fa-dashcube'},
    {label: 'fa forumbee', value: 'fa fa-forumbee'},
    {label: 'fa leanpub', value: 'fa fa-leanpub'},
    {label: 'fa sellsy', value: 'fa fa-sellsy'},
    {label: 'fa shirtsinbulk', value: 'fa fa-shirtsinbulk'},
    {label: 'fa simplybuilt', value: 'fa fa-simplybuilt'},
    {label: 'fa skyatlas', value: 'fa fa-skyatlas'},
    {label: 'fa cart plus', value: 'fa fa-cart-plus'},
    {label: 'fa cart arrow down', value: 'fa fa-cart-arrow-down'},
    {label: 'fa diamond', value: 'fa fa-diamond'},
    {label: 'fa ship', value: 'fa fa-ship'},
    {label: 'fa user secret', value: 'fa fa-user-secret'},
    {label: 'fa motorcycle', value: 'fa fa-motorcycle'},
    {label: 'fa street view', value: 'fa fa-street-view'},
    {label: 'fa heartbeat', value: 'fa fa-heartbeat'},
    {label: 'fa venus', value: 'fa fa-venus'},
    {label: 'fa mars', value: 'fa fa-mars'},
    {label: 'fa mercury', value: 'fa fa-mercury'},
    {label: 'fa transgender', value: 'fa fa-transgender'},
    {label: 'fa transgender alt', value: 'fa fa-transgender-alt'},
    {label: 'fa venus double', value: 'fa fa-venus-double'},
    {label: 'fa mars double', value: 'fa fa-mars-double'},
    {label: 'fa venus mars', value: 'fa fa-venus-mars'},
    {label: 'fa mars stroke', value: 'fa fa-mars-stroke'},
    {label: 'fa mars stroke v', value: 'fa fa-mars-stroke-v'},
    {label: 'fa mars stroke h', value: 'fa fa-mars-stroke-h'},
    {label: 'fa neuter', value: 'fa fa-neuter'},
    {label: 'fa genderless', value: 'fa fa-genderless'},
    {label: 'fa facebook official', value: 'fa fa-facebook-official'},
    {label: 'fa pinterest p', value: 'fa fa-pinterest-p'},
    {label: 'fa whatsapp', value: 'fa fa-whatsapp'},
    {label: 'fa server', value: 'fa fa-server'},
    {label: 'fa user plus', value: 'fa fa-user-plus'},
    {label: 'fa user times', value: 'fa fa-user-times'},
    {label: 'fa bed', value: 'fa fa-bed'},
    {label: 'fa viacoin', value: 'fa fa-viacoin'},
    {label: 'fa train', value: 'fa fa-train'},
    {label: 'fa subway', value: 'fa fa-subway'},
    {label: 'fa medium', value: 'fa fa-medium'},
    {label: 'fa y combinator', value: 'fa fa-y-combinator'},
    {label: 'fa optin monster', value: 'fa fa-optin-monster'},
    {label: 'fa opencart', value: 'fa fa-opencart'},
    {label: 'fa expeditedssl', value: 'fa fa-expeditedssl'},
    {label: 'fa battery full', value: 'fa fa-battery-full'},
    {label: 'fa battery three quarters', value: 'fa fa-battery-three-quarters'},
    {label: 'fa battery half', value: 'fa fa-battery-half'},
    {label: 'fa battery quarter', value: 'fa fa-battery-quarter'},
    {label: 'fa battery empty', value: 'fa fa-battery-empty'},
    {label: 'fa mouse pointer', value: 'fa fa-mouse-pointer'},
    {label: 'fa i cursor', value: 'fa fa-i-cursor'},
    {label: 'fa object group', value: 'fa fa-object-group'},
    {label: 'fa object ungroup', value: 'fa fa-object-ungroup'},
    {label: 'fa sticky note', value: 'fa fa-sticky-note'},
    {label: 'fa sticky note o', value: 'fa fa-sticky-note-o'},
    {label: 'fa cc jcb', value: 'fa fa-cc-jcb'},
    {label: 'fa cc diners club', value: 'fa fa-cc-diners-club'},
    {label: 'fa clone', value: 'fa fa-clone'},
    {label: 'fa balance scale', value: 'fa fa-balance-scale'},
    {label: 'fa hourglass o', value: 'fa fa-hourglass-o'},
    {label: 'fa hourglass start', value: 'fa fa-hourglass-start'},
    {label: 'fa hourglass half', value: 'fa fa-hourglass-half'},
    {label: 'fa hourglass end', value: 'fa fa-hourglass-end'},
    {label: 'fa hourglass', value: 'fa fa-hourglass'},
    {label: 'fa hand rock o', value: 'fa fa-hand-rock-o'},
    {label: 'fa hand paper o', value: 'fa fa-hand-paper-o'},
    {label: 'fa hand scissors o', value: 'fa fa-hand-scissors-o'},
    {label: 'fa hand lizard o', value: 'fa fa-hand-lizard-o'},
    {label: 'fa hand spock o', value: 'fa fa-hand-spock-o'},
    {label: 'fa hand pointer o', value: 'fa fa-hand-pointer-o'},
    {label: 'fa hand peace o', value: 'fa fa-hand-peace-o'},
    {label: 'fa trademark', value: 'fa fa-trademark'},
    {label: 'fa registered', value: 'fa fa-registered'},
    {label: 'fa creative commons', value: 'fa fa-creative-commons'},
    {label: 'fa gg', value: 'fa fa-gg'},
    {label: 'fa gg circle', value: 'fa fa-gg-circle'},
    {label: 'fa tripadvisor', value: 'fa fa-tripadvisor'},
    {label: 'fa odnoklassniki', value: 'fa fa-odnoklassniki'},
    {label: 'fa odnoklassniki square', value: 'fa fa-odnoklassniki-square'},
    {label: 'fa get pocket', value: 'fa fa-get-pocket'},
    {label: 'fa wikipedia w', value: 'fa fa-wikipedia-w'},
    {label: 'fa safari', value: 'fa fa-safari'},
    {label: 'fa chrome', value: 'fa fa-chrome'},
    {label: 'fa firefox', value: 'fa fa-firefox'},
    {label: 'fa opera', value: 'fa fa-opera'},
    {label: 'fa internet explorer', value: 'fa fa-internet-explorer'},
    {label: 'fa television', value: 'fa fa-television'},
    {label: 'fa contao', value: 'fa fa-contao'},
    {label: 'fa 500px', value: 'fa fa-500px'},
    {label: 'fa amazon', value: 'fa fa-amazon'},
    {label: 'fa calendar plus o', value: 'fa fa-calendar-plus-o'},
    {label: 'fa calendar minus o', value: 'fa fa-calendar-minus-o'},
    {label: 'fa calendar times o', value: 'fa fa-calendar-times-o'},
    {label: 'fa calendar check o', value: 'fa fa-calendar-check-o'},
    {label: 'fa industry', value: 'fa fa-industry'},
    {label: 'fa map pin', value: 'fa fa-map-pin'},
    {label: 'fa map signs', value: 'fa fa-map-signs'},
    {label: 'fa map o', value: 'fa fa-map-o'},
    {label: 'fa map', value: 'fa fa-map'},
    {label: 'fa commenting', value: 'fa fa-commenting'},
    {label: 'fa commenting o', value: 'fa fa-commenting-o'},
    {label: 'fa houzz', value: 'fa fa-houzz'},
    {label: 'fa vimeo', value: 'fa fa-vimeo'},
    {label: 'fa black tie', value: 'fa fa-black-tie'},
    {label: 'fa fonticons', value: 'fa fa-fonticons'},
    {label: 'fa reddit alien', value: 'fa fa-reddit-alien'},
    {label: 'fa edge', value: 'fa fa-edge'},
    {label: 'fa credit card alt', value: 'fa fa-credit-card-alt'},
    {label: 'fa codiepie', value: 'fa fa-codiepie'},
    {label: 'fa modx', value: 'fa fa-modx'},
    {label: 'fa fort awesome', value: 'fa fa-fort-awesome'},
    {label: 'fa usb', value: 'fa fa-usb'},
    {label: 'fa product hunt', value: 'fa fa-product-hunt'},
    {label: 'fa mixcloud', value: 'fa fa-mixcloud'},
    {label: 'fa scribd', value: 'fa fa-scribd'},
    {label: 'fa pause circle', value: 'fa fa-pause-circle'},
    {label: 'fa pause circle o', value: 'fa fa-pause-circle-o'},
    {label: 'fa stop circle', value: 'fa fa-stop-circle'},
    {label: 'fa stop circle o', value: 'fa fa-stop-circle-o'},
    {label: 'fa shopping bag', value: 'fa fa-shopping-bag'},
    {label: 'fa shopping basket', value: 'fa fa-shopping-basket'},
    {label: 'fa hashtag', value: 'fa fa-hashtag'},
    {label: 'fa bluetooth', value: 'fa fa-bluetooth'},
    {label: 'fa bluetooth b', value: 'fa fa-bluetooth-b'},
    {label: 'fa percent', value: 'fa fa-percent'},
    {label: 'fa gitlab', value: 'fa fa-gitlab'},
    {label: 'fa wpbeginner', value: 'fa fa-wpbeginner'},
    {label: 'fa wpforms', value: 'fa fa-wpforms'},
    {label: 'fa envira', value: 'fa fa-envira'},
    {label: 'fa universal access', value: 'fa fa-universal-access'},
    {label: 'fa wheelchair alt', value: 'fa fa-wheelchair-alt'},
    {label: 'fa question circle o', value: 'fa fa-question-circle-o'},
    {label: 'fa blind', value: 'fa fa-blind'},
    {label: 'fa audio description', value: 'fa fa-audio-description'},
    {label: 'fa volume control phone', value: 'fa fa-volume-control-phone'},
    {label: 'fa braille', value: 'fa fa-braille'},
    {label: 'fa assistive listening systems', value: 'fa fa-assistive-listening-systems'},
    {label: 'fa american sign language interpreting', value: 'fa fa-american-sign-language-interpreting'},
    {label: 'fa deaf', value: 'fa fa-deaf'},
    {label: 'fa glide', value: 'fa fa-glide'},
    {label: 'fa glide g', value: 'fa fa-glide-g'},
    {label: 'fa sign language', value: 'fa fa-sign-language'},
    {label: 'fa low vision', value: 'fa fa-low-vision'},
    {label: 'fa viadeo', value: 'fa fa-viadeo'},
    {label: 'fa viadeo square', value: 'fa fa-viadeo-square'},
    {label: 'fa snapchat', value: 'fa fa-snapchat'},
    {label: 'fa snapchat ghost', value: 'fa fa-snapchat-ghost'},
    {label: 'fa snapchat square', value: 'fa fa-snapchat-square'},
    {label: 'fa pied piper', value: 'fa fa-pied-piper'},
    {label: 'fa first order', value: 'fa fa-first-order'},
    {label: 'fa yoast', value: 'fa fa-yoast'},
    {label: 'fa themeisle', value: 'fa fa-themeisle'},
    {label: 'fa google plus official', value: 'fa fa-google-plus-official'},
    {label: 'fa font awesome', value: 'fa fa-font-awesome'},
    {label: 'fa handshake o', value: 'fa fa-handshake-o'},
    {label: 'fa envelope open', value: 'fa fa-envelope-open'},
    {label: 'fa envelope open o', value: 'fa fa-envelope-open-o'},
    {label: 'fa linode', value: 'fa fa-linode'},
    {label: 'fa address book', value: 'fa fa-address-book'},
    {label: 'fa address book o', value: 'fa fa-address-book-o'},
    {label: 'fa address card', value: 'fa fa-address-card'},
    {label: 'fa address card o', value: 'fa fa-address-card-o'},
    {label: 'fa user circle', value: 'fa fa-user-circle'},
    {label: 'fa user circle o', value: 'fa fa-user-circle-o'},
    {label: 'fa user o', value: 'fa fa-user-o'},
    {label: 'fa id badge', value: 'fa fa-id-badge'},
    {label: 'fa id card', value: 'fa fa-id-card'},
    {label: 'fa id card o', value: 'fa fa-id-card-o'},
    {label: 'fa quora', value: 'fa fa-quora'},
    {label: 'fa free code camp', value: 'fa fa-free-code-camp'},
    {label: 'fa telegram', value: 'fa fa-telegram'},
    {label: 'fa thermometer full', value: 'fa fa-thermometer-full'},
    {label: 'fa thermometer three quarters', value: 'fa fa-thermometer-three-quarters'},
    {label: 'fa thermometer half', value: 'fa fa-thermometer-half'},
    {label: 'fa thermometer quarter', value: 'fa fa-thermometer-quarter'},
    {label: 'fa thermometer empty', value: 'fa fa-thermometer-empty'},
    {label: 'fa shower', value: 'fa fa-shower'},
    {label: 'fa bath', value: 'fa fa-bath'},
    {label: 'fa podcast', value: 'fa fa-podcast'},
    {label: 'fa window maximize', value: 'fa fa-window-maximize'},
    {label: 'fa window minimize', value: 'fa fa-window-minimize'},
    {label: 'fa window restore', value: 'fa fa-window-restore'},
    {label: 'fa window close', value: 'fa fa-window-close'},
    {label: 'fa window close o', value: 'fa fa-window-close-o'},
    {label: 'fa bandcamp', value: 'fa fa-bandcamp'},
    {label: 'fa grav', value: 'fa fa-grav'},
    {label: 'fa etsy', value: 'fa fa-etsy'},
    {label: 'fa imdb', value: 'fa fa-imdb'},
    {label: 'fa ravelry', value: 'fa fa-ravelry'},
    {label: 'fa eercast', value: 'fa fa-eercast'},
    {label: 'fa microchip', value: 'fa fa-microchip'},
    {label: 'fa snowflake o', value: 'fa fa-snowflake-o'},
    {label: 'fa superpowers', value: 'fa fa-superpowers'},
    {label: 'fa wpexplorer', value: 'fa fa-wpexplorer'},
    {label: 'fa meetup', value: 'fa fa-meetup'}
];

export const SEVERITY_VALUES: SelectItem[] = [
    {label: 'info', value: 'info'},
    {label: 'success', value: 'success'},
    {label: 'warn', value: 'warn'},
    {label: 'error', value: 'error'},
];
