import {SelectItem} from 'primeng/api';

export const APP_VERSION = '4.1.8';

export const MAP_INPUT_TO_FIELD: Map<string, any> = new Map(
    [
        ['string', ['input', 'text']],
        ['number', ['input', 'number']],
        ['decimal', ['input', 'decimal']],
        ['password', ['input', 'password']],
        ['email', ['input', 'email']],
        ['text', ['textarea', null]],
        ['tinymce', ['tinymce', null]],
        ['monaco', ['monaco', null]],
        ['boolean', ['checkbox', null]],
        ['passivation', ['checkbox', 'passivation']],
        ['date', ['date', null]],
        ['datetime', ['datetime', null]],
        ['time', ['time', null]],
        ['select', ['select', null]],
        ['media', ['media', null]],
        ['image', ['image', null]],
        ['tags', ['tags', null]],
        ['join', ['join', null]],
        ['multijoin', ['multijoin', null]],
        ['realtionships', ['realtionships', null]],
        ['gmaplocation', ['gmaplocation', null]],
        ['gmappath', ['gmappath', null]]
    ]
);

const FA6_BRAND_ICONS = new Set<string>([
    '500px', 'adn', 'amazon', 'android', 'angellist', 'apple', 'bandcamp', 'behance', 'behance-square',
    'bitbucket', 'bitbucket-square', 'black-tie', 'bluetooth', 'bluetooth-b', 'buysellads', 'cc-amex',
    'cc-diners-club', 'cc-discover', 'cc-jcb', 'cc-mastercard', 'cc-paypal', 'cc-stripe', 'cc-visa', 'chrome',
    'codepen', 'codiepie', 'connectdevelop', 'contao', 'css3', 'dashcube', 'delicious', 'deviantart', 'digg',
    'discord', 'dribbble', 'dropbox', 'drupal', 'edge', 'eercast', 'empire', 'envira', 'etsy', 'expeditedssl',
    'facebook', 'facebook-f', 'facebook-official', 'facebook-square', 'firefox', 'flickr', 'font-awesome',
    'fonticons', 'fort-awesome', 'forumbee', 'foursquare', 'free-code-camp', 'git', 'git-square', 'github',
    'github-alt', 'github-square', 'gitlab', 'glide', 'glide-g', 'google', 'google-plus', 'google-plus-circle',
    'google-plus-official', 'google-plus-square', 'google-wallet', 'gratipay', 'grav', 'hacker-news', 'houzz',
    'html5', 'imdb', 'instagram', 'internet-explorer', 'ioxhost', 'joomla', 'jsfiddle', 'lastfm',
    'lastfm-square', 'leanpub', 'linode', 'linkedin', 'linkedin-square', 'linux', 'maxcdn', 'meanpath', 'medium',
    'meetup', 'mixcloud', 'modx', 'odnoklassniki', 'odnoklassniki-square', 'opencart', 'opera', 'optin-monster',
    'pagelines', 'paypal', 'pied-piper', 'pied-piper-alt', 'pied-piper-pp', 'pinterest', 'pinterest-p',
    'pinterest-square', 'product-hunt', 'qq', 'quora', 'ravelry', 'rebel', 'reddit', 'reddit-alien',
    'reddit-square', 'renren', 'safari', 'scribd', 'sellsy', 'shirtsinbulk', 'simplybuilt', 'skyatlas', 'skype',
    'slack', 'slideshare', 'snapchat', 'snapchat-ghost', 'snapchat-square', 'soundcloud', 'spotify',
    'stack-exchange', 'stack-overflow', 'steam', 'steam-square', 'stumbleupon', 'stumbleupon-circle',
    'superpowers', 'telegram', 'tencent-weibo', 'themeisle', 'trello', 'tripadvisor', 'tumblr',
    'tumblr-square', 'twitch', 'twitter', 'twitter-square', 'usb', 'viacoin', 'viadeo', 'viadeo-square', 'vimeo',
    'vimeo-square', 'vine', 'vk', 'wechat', 'weibo', 'weixin', 'whatsapp', 'wikipedia-w', 'windows',
    'wordpress', 'wpbeginner', 'wpexplorer', 'wpforms', 'xing', 'xing-square', 'y-combinator', 'yahoo', 'yelp',
    'yoast', 'youtube', 'youtube-play', 'youtube-square'
]);

const FA6_ICON_RENAMES: Record<string, string> = {
    'close': 'xmark',
    'remove': 'xmark',
    'mail-forward': 'share',
    'mail-reply': 'reply',
    'mail-reply-all': 'reply-all',
    'warning': 'triangle-exclamation',
    'dashboard': 'gauge-high',
    'chain-broken': 'link-slash',
    'automobile': 'car',
    'navicon': 'bars',
    'photo': 'image',
    'soccer-ball': 'futbol',
    'window-close': 'window-closed',
    'files': 'copy'
};

function toFa6IconClass(iconClass: string): string {
    const match = iconClass.match(/\bfa fa-([a-z0-9-]+)/);
    if (!match) {
        return iconClass;
    }

    let iconName = match[1];
    let style = 'fa-solid';

    if (iconName.endsWith('-o')) {
        iconName = iconName.slice(0, -2);
        style = 'fa-regular';
    }

    iconName = FA6_ICON_RENAMES[iconName] ?? iconName;

    if (FA6_BRAND_ICONS.has(iconName)) {
        style = 'fa-brands';
    }

    return `${style} fa-${iconName}`;
}

const UNSUPPORTED_FA6_ICON_NAMES = new Set<string>([
    'google-plus-official',
    'hand-up',
    'meanpath',
    'sort-alpha-asc',
    'sort-alpha-desc',
    'sort-amount-asc',
    'sort-amount-desc',
    'sort-numeric-asc',
    'sort-numeric-desc'
]);

function getLegacyFaIconName(iconClass: string): string | undefined {
    const match = iconClass.match(/\bfa fa-([a-z0-9-]+)/);
    return match?.[1];
}

function isSupportedLegacyIcon(icon: SelectItem): boolean {
    if (typeof icon.value !== 'string') {
        return true;
    }

    const iconName = getLegacyFaIconName(icon.value);
    return !iconName || !UNSUPPORTED_FA6_ICON_NAMES.has(iconName);
}

function dedupeIconsByValue(icons: SelectItem[]): SelectItem[] {
    const seen = new Set<string>();

    return icons.filter((icon) => {
        const key = typeof icon.value === 'string' ? icon.value : JSON.stringify(icon.value);
        if (seen.has(key)) {
            return false;
        }

        seen.add(key);
        return true;
    });
}

export const ASSET_PATH = 'asset_path';
export const CHAT_API_PATH = 'chat_api_path';
export const CHATINTERACTIONS_API_PATH = 'chatinteractions_api_path';
export const CONDITION_API_PATH = 'condition_api_path';
export const DOCUMENT_API_PATH = 'document_api_path';
export const EXTENSION_API_PATH = 'extension_api_path';
export const EXPORT_API_PATH = 'export_api_path';
export const IMPORT_API_PATH = 'import_api_path';
export const FIELD_DEFINITION_API_PATH = 'field_definition_api_path';
export const LINKS_API_PATH = 'links_api_path';
export const METADATA_API_PATH = 'metadata_api_path';
export const DATA_LIST_API_PATH = 'data_list_api_path';
export const PUBLIC_DATA_API_PATH = 'public_data_api_path';
export const SELECT_QUERY_API_PATH = 'select_query_api_path';
export const AI_TOOLS_API_PATH = 'ai_tools_api_path';
export const USER_API_PATH = 'user_api_path';
export const ROLE_API_PATH = 'role_api_path';
export const USER_ROLES_API_PATH = 'user_roles_api_path';
export const URL_MAP_RULES_API_PATH = 'url_map_rules_api_path';
export const API_SERVICE_PATH = 'api_service_path';
export const LOGIN_API_PATH = 'login_api_path';
export const CHANGEPASSWORD_API_PATH = 'changepassword_api_path';
export const RESETPASSWORD_API_PATH = 'resetpassword_api_path';

export const CONFIG_PATH = '/assets/config.json';
export const DROPPABLE_API_PATH = 'droppable_api_path';
export const DRAGGABLE_API_PATH = 'draggable_api_path';
// se FS => /files/
// se S3 => /files/

// export const BASE_PATH = 'https://s3.eu-central-1.amazonaws.com/portale-si/';
export const BASE_PATH = '/files/';
export const TOKEN_ITEM = 'snello-token';
export const REFRESH_TOKEN_ITEM = 'snello-refresh-token';
export const USER_ITEM = 'snello-user';
export const CONTENT_TYPE = 'Content-Type';
export const APPLICATION_JSON = 'application/json';
export const AUTHORIZATION = 'Authorization';
export const BEARER_ = 'Bearer ';

const ADMIN_ITEMS_LEGACY: any[] = [
    {
        id: 'list',
        icon: 'fa fa-book',
        section: 'metadata',
        name: 'Metadata',
        summary: 'Metadata management on tables',
        roles: 'Admin, metadatas_edit, metadatas_view'
    },
    {
        id: 'list',
        icon: 'fa fa-hand-spock-o',
        section: 'condition',
        name: 'Condition',
        summary: 'Management of table filter conditions',
        roles: 'Admin, conditions_edit, conditions_view'
    },
    {
        id: 'list',
        icon: 'fa fa-files-o',
        section: 'document',
        name: 'Document',
        summary: 'Documents management',
        roles: 'Admin, documents_edit, documents_view'
    },
    {
        id: 'list',
        icon: 'fa fa-image',
        section: 'images',
        name: 'Images',
        summary: 'Images management',
        roles: 'Admin, documents_edit, documents_view'
    },
    {
        id: 'list',
        icon: 'fa fa-list',
        section: 'selectqueries',
        name: 'SelectQuery',
        summary: 'Select Queries Management',
        roles: 'Admin, selectqueries_edit, selectqueries_view'
    },
    {
        id: 'list',
        icon: 'fa fa-wrench',
        section: 'aitools',
        name: 'AiTools',
        summary: 'AI Tools Management',
        roles: 'Admin, aitools_edit, aitools_view, ai_tools_edit, ai_tools_view'
    },
    {
        id: 'list',
        icon: 'fa fa-link',
        section: 'links',
        name: 'Links',
        summary: 'Links Management',
        roles: 'Admin, links_edit, links_view'
    },
    {
        id: 'metadata',
        icon: 'fa fa-pencil-square',
        section: 'massive',
        name: 'Massive',
        summary: 'Massive Modifications',
        roles: 'Admin, metadatas_edit, metadatas_view'
    },
    {
        id: 'list',
        icon: 'fa fa-comments',
        section: 'chatinteractions',
        name: 'Chat Interactions',
        summary: 'Historical chat interactions',
        roles: 'Admin'
    },
    // {
    //     id: 'list',
    //     icon: 'fa fa-puzzle-piece',
    //     section: 'draggables',
    //     name: 'Draggables',
    //     summary: 'Draggables Management',
    //     roles: 'Admin, draggables_edit, draggables_view'
    // },
    // {
    //     id: 'list',
    //     icon: 'fa fa-shopping-basket',
    //     section: 'droppables',
    //     name: 'Droppables',
    //     summary: 'Droppables Management',
    //     roles: 'Admin, droppables_edit, droppables_view'
    // },
    // {
    //     id: 'list',
    //     icon: 'fa fa-plus-circle',
    //     section: 'extensions_admin',
    //     name: 'Extensions',
    //     summary: 'Extensions Management',
    //     roles: 'Admin, extensions_edit, extensions_view'
    // }
];

export const ADMIN_ITEMS: any[] = ADMIN_ITEMS_LEGACY.map((item) => ({
    ...item,
    icon: toFa6IconClass(item.icon)
}));

const FONT_AWESOME_ICONS_LEGACY: SelectItem[] = [
    {label: 'fa music', value: 'fa fa-music'},
    {label: 'fa search', value: 'fa fa-search'},
    {label: 'fa heart', value: 'fa fa-heart'},
    {label: 'fa star', value: 'fa fa-star'},
    {label: 'fa user', value: 'fa fa-user'},
    {label: 'fa film', value: 'fa fa-film'},
    {label: 'fa check', value: 'fa fa-check'},
    {label: 'fa times', value: 'fa fa-times'},
    {label: 'fa search plus', value: 'fa fa-search-plus'},
    {label: 'fa search minus', value: 'fa fa-search-minus'},
    {label: 'fa power off', value: 'fa fa-power-off'},
    {label: 'fa signal', value: 'fa fa-signal'},
    {label: 'fa cog', value: 'fa fa-cog'},
    {label: 'fa home', value: 'fa fa-home'},
    {label: 'fa inbox', value: 'fa fa-inbox'},
    {label: 'fa copy', value: 'fa fa-copy'},
    {label: 'fa refresh', value: 'fa fa-refresh'},
    {label: 'fa lock', value: 'fa fa-lock'},
    {label: 'fa flag', value: 'fa fa-flag'},
    {label: 'fa headphones', value: 'fa fa-headphones'},
    {label: 'fa volume off', value: 'fa fa-volume-off'},
    {label: 'fa volume down', value: 'fa fa-volume-down'},
    {label: 'fa volume up', value: 'fa fa-volume-up'},
    {label: 'fa qrcode', value: 'fa fa-qrcode'},
    {label: 'fa barcode', value: 'fa fa-barcode'},
    {label: 'fa tag', value: 'fa fa-tag'},
    {label: 'fa tags', value: 'fa fa-tags'},
    {label: 'fa book', value: 'fa fa-book'},
    {label: 'fa bookmark', value: 'fa fa-bookmark'},
    {label: 'fa print', value: 'fa fa-print'},
    {label: 'fa camera', value: 'fa fa-camera'},
    {label: 'fa font', value: 'fa fa-font'},
    {label: 'fa bold', value: 'fa fa-bold'},
    {label: 'fa italic', value: 'fa fa-italic'},
    {label: 'fa align left', value: 'fa fa-align-left'},
    {label: 'fa align center', value: 'fa fa-align-center'},
    {label: 'fa align right', value: 'fa fa-align-right'},
    {label: 'fa align justify', value: 'fa fa-align-justify'},
    {label: 'fa list', value: 'fa fa-list'},
    {label: 'fa outdent', value: 'fa fa-outdent'},
    {label: 'fa indent', value: 'fa fa-indent'},
    {label: 'fa video camera', value: 'fa fa-video-camera'},
    {label: 'fa pencil', value: 'fa fa-pencil'},
    {label: 'fa map marker', value: 'fa fa-map-marker'},
    {label: 'fa adjust', value: 'fa fa-adjust'},
    {label: 'fa tint', value: 'fa fa-tint'},
    {label: 'fa arrows', value: 'fa fa-arrows'},
    {label: 'fa step backward', value: 'fa fa-step-backward'},
    {label: 'fa fast backward', value: 'fa fa-fast-backward'},
    {label: 'fa backward', value: 'fa fa-backward'},
    {label: 'fa play', value: 'fa fa-play'},
    {label: 'fa pause', value: 'fa fa-pause'},
    {label: 'fa stop', value: 'fa fa-stop'},
    {label: 'fa forward', value: 'fa fa-forward'},
    {label: 'fa fast forward', value: 'fa fa-fast-forward'},
    {label: 'fa step forward', value: 'fa fa-step-forward'},
    {label: 'fa eject', value: 'fa fa-eject'},
    {label: 'fa chevron left', value: 'fa fa-chevron-left'},
    {label: 'fa chevron right', value: 'fa fa-chevron-right'},
    {label: 'fa plus circle', value: 'fa fa-plus-circle'},
    {label: 'fa minus circle', value: 'fa fa-minus-circle'},
    {label: 'fa times circle', value: 'fa fa-times-circle'},
    {label: 'fa check circle', value: 'fa fa-check-circle'},
    {label: 'fa question circle', value: 'fa fa-question-circle'},
    {label: 'fa info circle', value: 'fa fa-info-circle'},
    {label: 'fa crosshairs', value: 'fa fa-crosshairs'},
    {label: 'fa ban', value: 'fa fa-ban'},
    {label: 'fa arrow left', value: 'fa fa-arrow-left'},
    {label: 'fa arrow right', value: 'fa fa-arrow-right'},
    {label: 'fa arrow up', value: 'fa fa-arrow-up'},
    {label: 'fa arrow down', value: 'fa fa-arrow-down'},
    {label: 'fa share', value: 'fa fa-share'},
    {label: 'fa expand', value: 'fa fa-expand'},
    {label: 'fa compress', value: 'fa fa-compress'},
    {label: 'fa plus', value: 'fa fa-plus'},
    {label: 'fa minus', value: 'fa fa-minus'},
    {label: 'fa asterisk', value: 'fa fa-asterisk'},
    {label: 'fa exclamation circle', value: 'fa fa-exclamation-circle'},
    {label: 'fa gift', value: 'fa fa-gift'},
    {label: 'fa leaf', value: 'fa fa-leaf'},
    {label: 'fa fire', value: 'fa fa-fire'},
    {label: 'fa eye', value: 'fa fa-eye'},
    {label: 'fa eye slash', value: 'fa fa-eye-slash'},
    {label: 'fa exclamation triangle', value: 'fa fa-exclamation-triangle'},
    {label: 'fa plane', value: 'fa fa-plane'},
    {label: 'fa calendar', value: 'fa fa-calendar'},
    {label: 'fa random', value: 'fa fa-random'},
    {label: 'fa comment', value: 'fa fa-comment'},
    {label: 'fa magnet', value: 'fa fa-magnet'},
    {label: 'fa chevron up', value: 'fa fa-chevron-up'},
    {label: 'fa chevron down', value: 'fa fa-chevron-down'},
    {label: 'fa retweet', value: 'fa fa-retweet'},
    {label: 'fa shopping cart', value: 'fa fa-shopping-cart'},
    {label: 'fa folder', value: 'fa fa-folder'},
    {label: 'fa folder open', value: 'fa fa-folder-open'},
    {label: 'fa arrows v', value: 'fa fa-arrows-v'},
    {label: 'fa arrows h', value: 'fa fa-arrows-h'},
    {label: 'fa twitter', value: 'fa fa-twitter'},
    {label: 'fa facebook', value: 'fa fa-facebook'},
    {label: 'fa github', value: 'fa fa-github'},
    {label: 'fa unlock', value: 'fa fa-unlock'},
    {label: 'fa credit card', value: 'fa fa-credit-card'},
    {label: 'fa rss', value: 'fa fa-rss'},
    {label: 'fa bullhorn', value: 'fa fa-bullhorn'},
    {label: 'fa bell', value: 'fa fa-bell'},
    {label: 'fa certificate', value: 'fa fa-certificate'},
    {label: 'fa arrow circle left', value: 'fa fa-arrow-circle-left'},
    {label: 'fa arrow circle right', value: 'fa fa-arrow-circle-right'},
    {label: 'fa arrow circle up', value: 'fa fa-arrow-circle-up'},
    {label: 'fa arrow circle down', value: 'fa fa-arrow-circle-down'},
    {label: 'fa globe', value: 'fa fa-globe'},
    {label: 'fa wrench', value: 'fa fa-wrench'},
    {label: 'fa tasks', value: 'fa fa-tasks'},
    {label: 'fa filter', value: 'fa fa-filter'},
    {label: 'fa briefcase', value: 'fa fa-briefcase'},
    {label: 'fa arrows alt', value: 'fa fa-arrows-alt'},
    {label: 'fa users', value: 'fa fa-users'},
    {label: 'fa link', value: 'fa fa-link'},
    {label: 'fa cloud', value: 'fa fa-cloud'},
    {label: 'fa flask', value: 'fa fa-flask'},
    {label: 'fa scissors', value: 'fa fa-scissors'},
    {label: 'fa paperclip', value: 'fa fa-paperclip'},
    {label: 'fa square', value: 'fa fa-square'},
    {label: 'fa bars', value: 'fa fa-bars'},
    {label: 'fa list ul', value: 'fa fa-list-ul'},
    {label: 'fa list ol', value: 'fa fa-list-ol'},
    {label: 'fa strikethrough', value: 'fa fa-strikethrough'},
    {label: 'fa underline', value: 'fa fa-underline'},
    {label: 'fa table', value: 'fa fa-table'},
    {label: 'fa truck', value: 'fa fa-truck'},
    {label: 'fa pinterest', value: 'fa fa-pinterest'},
    {label: 'fa key', value: 'fa fa-key'},
    {label: 'fa cogs', value: 'fa fa-cogs'},
    {label: 'fa comments', value: 'fa fa-comments'},
    {label: 'fa bolt', value: 'fa fa-bolt'},
    {label: 'fa sitemap', value: 'fa fa-sitemap'},
    {label: 'fa umbrella', value: 'fa fa-umbrella'},
    {label: 'fa clipboard', value: 'fa fa-clipboard'},
    {label: 'fa exchange', value: 'fa fa-exchange'},
    {label: 'fa cloud download', value: 'fa fa-cloud-download'},
    {label: 'fa cloud upload', value: 'fa fa-cloud-upload'},
    {label: 'fa user md', value: 'fa fa-user-md'},
    {label: 'fa stethoscope', value: 'fa fa-stethoscope'},
    {label: 'fa suitcase', value: 'fa fa-suitcase'},
    {label: 'fa coffee', value: 'fa fa-coffee'},
    {label: 'fa cutlery', value: 'fa fa-cutlery'},
    {label: 'fa ambulance', value: 'fa fa-ambulance'},
    {label: 'fa medkit', value: 'fa fa-medkit'},
    {label: 'fa fighter jet', value: 'fa fa-fighter-jet'},
    {label: 'fa beer', value: 'fa fa-beer'},
    {label: 'fa plus square', value: 'fa fa-plus-square'},
    {label: 'fa angle double left', value: 'fa fa-angle-double-left'},
    {label: 'fa angle double right', value: 'fa fa-angle-double-right'},
    {label: 'fa angle double up', value: 'fa fa-angle-double-up'},
    {label: 'fa angle double down', value: 'fa fa-angle-double-down'},
    {label: 'fa angle left', value: 'fa fa-angle-left'},
    {label: 'fa angle right', value: 'fa fa-angle-right'},
    {label: 'fa angle up', value: 'fa fa-angle-up'},
    {label: 'fa angle down', value: 'fa fa-angle-down'},
    {label: 'fa desktop', value: 'fa fa-desktop'},
    {label: 'fa laptop', value: 'fa fa-laptop'},
    {label: 'fa tablet', value: 'fa fa-tablet'},
    {label: 'fa mobile', value: 'fa fa-mobile'},
    {label: 'fa circle', value: 'fa fa-circle'},
    {label: 'fa quote left', value: 'fa fa-quote-left'},
    {label: 'fa quote right', value: 'fa fa-quote-right'},
    {label: 'fa spinner', value: 'fa fa-spinner'},
    {label: 'fa reply', value: 'fa fa-reply'},
    {label: 'fa github alt', value: 'fa fa-github-alt'},
    {label: 'fa gamepad', value: 'fa fa-gamepad'},
    {label: 'fa flag checkered', value: 'fa fa-flag-checkered'},
    {label: 'fa terminal', value: 'fa fa-terminal'},
    {label: 'fa code', value: 'fa fa-code'},
    {label: 'fa reply all', value: 'fa fa-reply-all'},
    {label: 'fa location arrow', value: 'fa fa-location-arrow'},
    {label: 'fa crop', value: 'fa fa-crop'},
    {label: 'fa code fork', value: 'fa fa-code-fork'},
    {label: 'fa question', value: 'fa fa-question'},
    {label: 'fa info', value: 'fa fa-info'},
    {label: 'fa exclamation', value: 'fa fa-exclamation'},
    {label: 'fa superscript', value: 'fa fa-superscript'},
    {label: 'fa subscript', value: 'fa fa-subscript'},
    {label: 'fa eraser', value: 'fa fa-eraser'},
    {label: 'fa puzzle piece', value: 'fa fa-puzzle-piece'},
    {label: 'fa microphone', value: 'fa fa-microphone'},
    {label: 'fa microphone slash', value: 'fa fa-microphone-slash'},
    {label: 'fa shield', value: 'fa fa-shield'},
    {label: 'fa fire extinguisher', value: 'fa fa-fire-extinguisher'},
    {label: 'fa rocket', value: 'fa fa-rocket'},
    {label: 'fa chevron circle left', value: 'fa fa-chevron-circle-left'},
    {label: 'fa chevron circle right', value: 'fa fa-chevron-circle-right'},
    {label: 'fa chevron circle up', value: 'fa fa-chevron-circle-up'},
    {label: 'fa chevron circle down', value: 'fa fa-chevron-circle-down'},
    {label: 'fa html5', value: 'fa fa-html5'},
    {label: 'fa css3', value: 'fa fa-css3'},
    {label: 'fa anchor', value: 'fa fa-anchor'},
    {label: 'fa unlock alt', value: 'fa fa-unlock-alt'},
    {label: 'fa bullseye', value: 'fa fa-bullseye'},
    {label: 'fa ellipsis h', value: 'fa fa-ellipsis-h'},
    {label: 'fa ellipsis v', value: 'fa fa-ellipsis-v'},
    {label: 'fa rss square', value: 'fa fa-rss-square'},
    {label: 'fa play circle', value: 'fa fa-play-circle'},
    {label: 'fa ticket', value: 'fa fa-ticket'},
    {label: 'fa minus square', value: 'fa fa-minus-square'},
    {label: 'fa level up', value: 'fa fa-level-up'},
    {label: 'fa level down', value: 'fa fa-level-down'},
    {label: 'fa check square', value: 'fa fa-check-square'},
    {label: 'fa compass', value: 'fa fa-compass'},
    {label: 'fa eur', value: 'fa fa-eur'},
    {label: 'fa gbp', value: 'fa fa-gbp'},
    {label: 'fa usd', value: 'fa fa-usd'},
    {label: 'fa inr', value: 'fa fa-inr'},
    {label: 'fa jpy', value: 'fa fa-jpy'},
    {label: 'fa rub', value: 'fa fa-rub'},
    {label: 'fa krw', value: 'fa fa-krw'},
    {label: 'fa btc', value: 'fa fa-btc'},
    {label: 'fa file', value: 'fa fa-file'},
    {label: 'fa file text', value: 'fa fa-file-text'},
    {label: 'fa sort alpha asc', value: 'fa fa-sort-alpha-asc'},
    {label: 'fa sort alpha desc', value: 'fa fa-sort-alpha-desc'},
    {label: 'fa sort amount asc', value: 'fa fa-sort-amount-asc'},
    {label: 'fa sort amount desc', value: 'fa fa-sort-amount-desc'},
    {label: 'fa sort numeric asc', value: 'fa fa-sort-numeric-asc'},
    {label: 'fa sort numeric desc', value: 'fa fa-sort-numeric-desc'},
    {label: 'fa thumbs up', value: 'fa fa-thumbs-up'},
    {label: 'fa thumbs down', value: 'fa fa-thumbs-down'},
    {label: 'fa youtube square', value: 'fa fa-youtube-square'},
    {label: 'fa youtube', value: 'fa fa-youtube'},
    {label: 'fa xing', value: 'fa fa-xing'},
    {label: 'fa xing square', value: 'fa fa-xing-square'},
    {label: 'fa youtube play', value: 'fa fa-youtube-play'},
    {label: 'fa dropbox', value: 'fa fa-dropbox'},
    {label: 'fa stack overflow', value: 'fa fa-stack-overflow'},
    {label: 'fa instagram', value: 'fa fa-instagram'},
    {label: 'fa flickr', value: 'fa fa-flickr'},
    {label: 'fa adn', value: 'fa fa-adn'},
    {label: 'fa bitbucket', value: 'fa fa-bitbucket'},
    {label: 'fa bitbucket square', value: 'fa fa-bitbucket-square'},
    {label: 'fa tumblr', value: 'fa fa-tumblr'},
    {label: 'fa tumblr square', value: 'fa fa-tumblr-square'},
    {label: 'fa long arrow down', value: 'fa fa-long-arrow-down'},
    {label: 'fa long arrow up', value: 'fa fa-long-arrow-up'},
    {label: 'fa long arrow left', value: 'fa fa-long-arrow-left'},
    {label: 'fa long arrow right', value: 'fa fa-long-arrow-right'},
    {label: 'fa apple', value: 'fa fa-apple'},
    {label: 'fa windows', value: 'fa fa-windows'},
    {label: 'fa android', value: 'fa fa-android'},
    {label: 'fa linux', value: 'fa fa-linux'},
    {label: 'fa dribbble', value: 'fa fa-dribbble'},
    {label: 'fa skype', value: 'fa fa-skype'},
    {label: 'fa foursquare', value: 'fa fa-foursquare'},
    {label: 'fa trello', value: 'fa fa-trello'},
    {label: 'fa feminine', value: 'fa fa-feminine'},
    {label: 'fa masculine', value: 'fa fa-masculine'},
    {label: 'fa gittip', value: 'fa fa-gittip'},
    {label: 'fa sun', value: 'fa fa-sun'},
    {label: 'fa moon', value: 'fa fa-moon'},
    {label: 'fa archive', value: 'fa fa-archive'},
    {label: 'fa bug', value: 'fa fa-bug'},
    {label: 'fa vk', value: 'fa fa-vk'},
    {label: 'fa weibo', value: 'fa fa-weibo'},
    {label: 'fa renren', value: 'fa fa-renren'},
    {label: 'fa pagelines', value: 'fa fa-pagelines'},
    {label: 'fa stack exchange', value: 'fa fa-stack-exchange'},
    {label: 'fa arrow circle o down', value: 'fa fa-arrow-circle-o-down'},
    {label: 'fa arrow circle o up', value: 'fa fa-arrow-circle-o-up'},
    {label: 'fa toggle down', value: 'fa fa-toggle-down'},
    {label: 'fa toggle up', value: 'fa fa-toggle-up'},
    {label: 'fa toggle right', value: 'fa fa-toggle-right'},
    {label: 'fa euro', value: 'fa fa-euro'},
    {label: 'fa gbp', value: 'fa fa-gbp'},
    {label: 'fa dollar', value: 'fa fa-dollar'},
    {label: 'fa rupee', value: 'fa fa-rupee'},
    {label: 'fa cny', value: 'fa fa-cny'},
    {label: 'fa ruble', value: 'fa fa-ruble'},
    {label: 'fa won', value: 'fa fa-won'},
    {label: 'fa bitcoin', value: 'fa fa-bitcoin'},
    {label: 'fa file archive', value: 'fa fa-file-archive'},
    {label: 'fa file image', value: 'fa fa-file-image'},
    {label: 'fa file movie', value: 'fa fa-file-movie'},
    {label: 'fa file pdf', value: 'fa fa-file-pdf'},
    {label: 'fa file code', value: 'fa fa-file-code'},
    {label: 'fa vine', value: 'fa fa-vine'},
    {label: 'fa codepen', value: 'fa fa-codepen'},
    {label: 'fa jsfiddle', value: 'fa fa-jsfiddle'},
    {label: 'fa life ring', value: 'fa fa-life-ring'},
    {label: 'fa circle o notch', value: 'fa fa-circle-o-notch'},
    {label: 'fa rebel', value: 'fa fa-rebel'},
    {label: 'fa empire', value: 'fa fa-empire'},
    {label: 'fa git square', value: 'fa fa-git-square'},
    {label: 'fa git', value: 'fa fa-git'},
    {label: 'fa hacker news', value: 'fa fa-hacker-news'},
    {label: 'fa tencent weibo', value: 'fa fa-tencent-weibo'},
    {label: 'fa qq', value: 'fa fa-qq'},
    {label: 'fa weixin', value: 'fa fa-weixin'},
    {label: 'fa paper plane', value: 'fa fa-paper-plane'},
    {label: 'fa mindmap', value: 'fa fa-mindmap'},
    {label: 'fa delete', value: 'fa fa-delete'},
    {label: 'fa graduation cap', value: 'fa fa-graduation-cap'},
    {label: 'fa yahoo', value: 'fa fa-yahoo'},
    {label: 'fa google', value: 'fa fa-google'},
    {label: 'fa reddit', value: 'fa fa-reddit'},
    {label: 'fa reddit square', value: 'fa fa-reddit-square'},
    {label: 'fa stumbleupon circle', value: 'fa fa-stumbleupon-circle'},
    {label: 'fa stumbleupon', value: 'fa fa-stumbleupon'},
    {label: 'fa delicious', value: 'fa fa-delicious'},
    {label: 'fa digg', value: 'fa fa-digg'},
    {label: 'fa pied piper', value: 'fa fa-pied-piper'},
    {label: 'fa pied piper alt', value: 'fa fa-pied-piper-alt'},
    {label: 'fa drupal', value: 'fa fa-drupal'},
    {label: 'fa joomla', value: 'fa fa-joomla'},
    {label: 'fa language', value: 'fa fa-language'},
    {label: 'fa fax', value: 'fa fa-fax'},
    {label: 'fa building', value: 'fa fa-building'},
    {label: 'fa child', value: 'fa fa-child'},
    {label: 'fa paw', value: 'fa fa-paw'},
    {label: 'fa spoon', value: 'fa fa-spoon'},
    {label: 'fa cube', value: 'fa fa-cube'},
    {label: 'fa cubes', value: 'fa fa-cubes'},
    {label: 'fa behance', value: 'fa fa-behance'},
    {label: 'fa behance square', value: 'fa fa-behance-square'},
    {label: 'fa steam', value: 'fa fa-steam'},
    {label: 'fa steam square', value: 'fa fa-steam-square'},
    {label: 'fa recycle', value: 'fa fa-recycle'},
    {label: 'fa car', value: 'fa fa-car'},
    {label: 'fa taxi', value: 'fa fa-taxi'},
    {label: 'fa tree', value: 'fa fa-tree'},
    {label: 'fa spotify', value: 'fa fa-spotify'},
    {label: 'fa deviantart', value: 'fa fa-deviantart'},
    {label: 'fa soundcloud', value: 'fa fa-soundcloud'},
    {label: 'fa database', value: 'fa fa-database'},
    {label: 'fa file pdf', value: 'fa fa-file-pdf'},
    {label: 'fa file word', value: 'fa fa-file-word'},
    {label: 'fa file excel', value: 'fa fa-file-excel'},
    {label: 'fa file powerpoint', value: 'fa fa-file-powerpoint'},
    {label: 'fa file image', value: 'fa fa-file-image'},
    {label: 'fa file archive', value: 'fa fa-file-archive'},
    {label: 'fa file audio', value: 'fa fa-file-audio'},
    {label: 'fa file video', value: 'fa fa-file-video'},
    {label: 'fa header', value: 'fa fa-header'},
    {label: 'fa paragraph', value: 'fa fa-paragraph'},
    {label: 'fa sliders', value: 'fa fa-sliders'},
    {label: 'fa share alt', value: 'fa fa-share-alt'},
    {label: 'fa share alt square', value: 'fa fa-share-alt-square'},
    {label: 'fa bomb', value: 'fa fa-bomb'},
    {label: 'fa soccer ball', value: 'fa fa-soccer-ball'},
    {label: 'fa tty', value: 'fa fa-tty'},
    {label: 'fa binoculars', value: 'fa fa-binoculars'},
    {label: 'fa object group', value: 'fa fa-object-group'},
    {label: 'fa object ungroup', value: 'fa fa-object-ungroup'},
    {label: 'fa sticky note', value: 'fa fa-sticky-note'},
    {label: 'fa clone', value: 'fa fa-clone'},
    {label: 'fa balance scale', value: 'fa fa-balance-scale'},
    {label: 'fa hourglass start', value: 'fa fa-hourglass-start'},
    {label: 'fa hourglass half', value: 'fa fa-hourglass-half'},
    {label: 'fa hourglass end', value: 'fa fa-hourglass-end'},
    {label: 'fa hourglass', value: 'fa fa-hourglass'},
    {label: 'fa hand rock', value: 'fa fa-hand-rock'},
    {label: 'fa hand paper', value: 'fa fa-hand-paper'},
    {label: 'fa hand scissors', value: 'fa fa-hand-scissors'},
    {label: 'fa hand lizard', value: 'fa fa-hand-lizard'},
    {label: 'fa hand spock', value: 'fa fa-hand-spock'},
    {label: 'fa hand pointer', value: 'fa fa-hand-pointer'},
    {label: 'fa hand peace', value: 'fa fa-hand-peace'},
    {label: 'fa registered', value: 'fa fa-registered'},
    {label: 'fa creative commons', value: 'fa fa-creative-commons'},
    {label: 'fa gg', value: 'fa fa-gg'},
    {label: 'fa gg circle', value: 'fa fa-gg-circle'},
    {label: 'fa tripadvisor', value: 'fa fa-tripadvisor'},
    {label: 'fa odnoklassniki', value: 'fa fa-odnoklassniki'},
    {label: 'fa odnoklassniki square', value: 'fa fa-odnoklassniki-square'},
    {label: 'fa get pocket', value: 'fa fa-get-pocket'},
    {label: 'fa wikipedia w', value: 'fa fa-wikipedia-w'},
    {label: 'fa safari', value: 'fa fa-safari'},
    {label: 'fa chrome', value: 'fa fa-chrome'},
    {label: 'fa firefox', value: 'fa fa-firefox'},
    {label: 'fa opera', value: 'fa fa-opera'},
    {label: 'fa internet explorer', value: 'fa fa-internet-explorer'},
    {label: 'fa television', value: 'fa fa-television'},
    {label: 'fa contao', value: 'fa fa-contao'},
    {label: 'fa500px', value: 'fa fa-500px'},
    {label: 'fa amazon', value: 'fa fa-amazon'},
    {label: 'fa calendar plus', value: 'fa fa-calendar-plus'},
    {label: 'fa calendar minus', value: 'fa fa-calendar-minus'},
    {label: 'fa calendar times', value: 'fa fa-calendar-times'},
    {label: 'fa calendar check', value: 'fa fa-calendar-check'},
    {label: 'fa industry', value: 'fa fa-industry'},
    {label: 'fa map pin', value: 'fa fa-map-pin'},
    {label: 'fa map signs', value: 'fa fa-map-signs'},
    {label: 'fa map o', value: 'fa fa-map-o'},
    {label: 'fa map', value: 'fa fa-map'},
    {label: 'fa commenting', value: 'fa fa-commenting'},
    {label: 'fa commenting o', value: 'fa fa-commenting-o'},
    {label: 'fa houzz', value: 'fa fa-houzz'},
    {label: 'fa vimeo', value: 'fa fa-vimeo'},
    {label: 'fa black tie', value: 'fa fa-black-tie'},
    {label: 'fa fonticons', value: 'fa fa-fonticons'},
    {label: 'fa reddit alien', value: 'fa fa-reddit-alien'},
    {label: 'fa edge', value: 'fa fa-edge'},
    {label: 'fa credit card alt', value: 'fa fa-credit-card-alt'},
    {label: 'fa codiepie', value: 'fa fa-codiepie'},
    {label: 'fa modx', value: 'fa fa-modx'},
    {label: 'fa fort awesome', value: 'fa fa-fort-awesome'},
    {label: 'fa usb', value: 'fa fa-usb'},
    {label: 'fa product hunt', value: 'fa fa-product-hunt'},
    {label: 'fa mixcloud', value: 'fa fa-mixcloud'},
    {label: 'fa scribd', value: 'fa fa-scribd'},
    {label: 'fa pause circle', value: 'fa fa-pause-circle'},
    {label: 'fa stop circle', value: 'fa fa-stop-circle'},
    {label: 'fa shopping bag', value: 'fa fa-shopping-bag'},
    {label: 'fa shopping basket', value: 'fa fa-shopping-basket'},
    {label: 'fa hashtag', value: 'fa fa-hashtag'},
    {label: 'fa bluetooth', value: 'fa fa-bluetooth'},
    {label: 'fa bluetooth b', value: 'fa fa-bluetooth-b'},
    {label: 'fa percent', value: 'fa fa-percent'},
    {label: 'fa gitlab', value: 'fa fa-gitlab'},
    {label: 'fa wpbeginner', value: 'fa fa-wpbeginner'},
    {label: 'fa wpforms', value: 'fa fa-wpforms'},
    {label: 'fa envira', value: 'fa fa-envira'},
    {label: 'fa universal access', value: 'fa fa-universal-access'},
    {label: 'fa wheelchair alt', value: 'fa fa-wheelchair-alt'},
    {label: 'fa question circle o', value: 'fa fa-question-circle-o'},
    {label: 'fa blind', value: 'fa fa-blind'},
    {label: 'fa audio description', value: 'fa fa-audio-description'},
    {label: 'fa volume control phone', value: 'fa fa-volume-control-phone'},
    {label: 'fa braille', value: 'fa fa-braille'},
    {label: 'fa assistive listening systems', value: 'fa fa-assistive-listening-systems'},
    {label: 'fa asl interpreting', value: 'fa fa-asl-interpreting'},
    {label: 'fa deafness', value: 'fa fa-deafness'},
    {label: 'fa hard of hearing', value: 'fa fa-hard-of-hearing'},
    {label: 'fa sign language', value: 'fa fa-sign-language'},
    {label: 'fa low vision', value: 'fa fa-low-vision'},
    {label: 'fa viadeo', value: 'fa fa-viadeo'},
    {label: 'fa viadeo square', value: 'fa fa-viadeo-square'},
    {label: 'fa snapchat', value: 'fa fa-snapchat'},
    {label: 'fa snapchat ghost', value: 'fa fa-snapchat-ghost'},
    {label: 'fa snapchat square', value: 'fa fa-snapchat-square'},
    {label: 'fa first order', value: 'fa fa-first-order'},
    {label: 'fa yoast', value: 'fa fa-yoast'},
    {label: 'fa themeisle', value: 'fa fa-themeisle'},
    {label: 'fa google plus official', value: 'fa fa-google-plus-official'},
    {label: 'fa font awesome alt', value: 'fa fa-font-awesome-alt'},
    {label: 'fa linode', value: 'fa fa-linode'},
    {label: 'fa address book', value: 'fa fa-address-book'},
    {label: 'fa address card', value: 'fa fa-address-card'},
    {label: 'fa user circle', value: 'fa fa-user-circle'},
    {label: 'fa id badge', value: 'fa fa-id-badge'},
    {label: 'fa id card', value: 'fa fa-id-card'},
    {label: 'fa quora', value: 'fa fa-quora'},
    {label: 'fa free code camp', value: 'fa fa-free-code-camp'},
    {label: 'fa telegram', value: 'fa fa-telegram'},
    {label: 'fa thermometer', value: 'fa fa-thermometer'},
    {label: 'fa shower', value: 'fa fa-shower'},
    {label: 'fa bathtub', value: 'fa fa-bathtub'},
    {label: 'fa s15', value: 'fa fa-s15'},
    {label: 'fa bath', value: 'fa fa-bath'},
    {label: 'fa podcast', value: 'fa fa-podcast'},
    {label: 'fa window maximize', value: 'fa fa-window-maximize'},
    {label: 'fa window minimize', value: 'fa fa-window-minimize'},
    {label: 'fa window restore', value: 'fa fa-window-restore'},
    {label: 'fa times rectangle', value: 'fa fa-times-rectangle'},
    {label: 'fa window close', value: 'fa fa-window-close'},
    {label: 'fa bandcamp', value: 'fa fa-bandcamp'},
    {label: 'fa grav', value: 'fa fa-grav'},
    {label: 'fa etsy', value: 'fa fa-etsy'},
    {label: 'fa imdb', value: 'fa fa-imdb'},
    {label: 'fa ravelry', value: 'fa fa-ravelry'},
    {label: 'fa microchip', value: 'fa fa-microchip'},
    {label: 'fa snowflake', value: 'fa fa-snowflake'},
    {label: 'fa superpowers', value: 'fa fa-superpowers'},
    {label: 'fa wpexplorer', value: 'fa fa-wpexplorer'},
    {label: 'fa meetup', value: 'fa fa-meetup'},
    // Nuove icone moderne FA6
    {label: 'fa bell o', value: 'fa fa-bell'},
    {label: 'fa circle o', value: 'fa fa-circle'},
    {label: 'fa heart o', value: 'fa fa-heart'},
    {label: 'fa star o', value: 'fa fa-star'},
    {label: 'fa envelope o', value: 'fa fa-envelope'},
    {label: 'fa copy', value: 'fa fa-copy'},
    {label: 'fa clone', value: 'fa fa-clone'},
    {label: 'fa download', value: 'fa fa-download'},
    {label: 'fa inbox', value: 'fa fa-inbox'},
    {label: 'fa database', value: 'fa fa-database'},
    {label: 'fa chart bar', value: 'fa fa-chart-bar'},
    {label: 'fa chart line', value: 'fa fa-chart-line'},
    {label: 'fa bar chart', value: 'fa fa-bar-chart'},
    {label: 'fa line chart', value: 'fa fa-line-chart'},
    {label: 'fa pie chart', value: 'fa fa-pie-chart'},
    {label: 'fa spinner', value: 'fa fa-spinner'},
    {label: 'fa circle notch', value: 'fa fa-circle-notch'},
    {label: 'fa refresh', value: 'fa fa-refresh'},
    {label: 'fa sync', value: 'fa fa-sync'},
    {label: 'fa cog', value: 'fa fa-cog'},
    {label: 'fa gear', value: 'fa fa-cog'},
    {label: 'fa cogs', value: 'fa fa-cogs'},
    {label: 'fa power off', value: 'fa fa-power-off'},
    {label: 'fa trash', value: 'fa fa-trash'},
    {label: 'fa remove', value: 'fa fa-trash'},
    {label: 'fa recycle', value: 'fa fa-recycle'},
    {label: 'fa plus', value: 'fa fa-plus'},
    {label: 'fa minus', value: 'fa fa-minus'},
    {label: 'fa check', value: 'fa fa-check'},
    {label: 'fa x', value: 'fa fa-times'},
    {label: 'fa exclamation', value: 'fa fa-exclamation'},
    {label: 'fa question', value: 'fa fa-question'},
    {label: 'fa info', value: 'fa fa-info'},
    {label: 'fa lightbulb', value: 'fa fa-lightbulb'},
    {label: 'fa thumbs up', value: 'fa fa-thumbs-up'},
    {label: 'fa thumbs down', value: 'fa fa-thumbs-down'}
];

export const FONT_AWESOME_ICONS: SelectItem[] = dedupeIconsByValue(
    FONT_AWESOME_ICONS_LEGACY
        .filter((icon) => isSupportedLegacyIcon(icon))
        .map((icon) => ({
            ...icon,
            value: typeof icon.value === 'string' ? toFa6IconClass(icon.value) : icon.value
        }))
).sort((left, right) => String(left.label).localeCompare(String(right.label), 'it'));

export const SEVERITY_VALUES: SelectItem[] = [
    {label: 'info', value: 'info'},
    {label: 'success', value: 'success'},
    {label: 'warn', value: 'warn'},
    {label: 'error', value: 'error'},
];
