FROM nginx:1.14.1-alpine

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY dist/snello-admin /usr/share/nginx/html/snello-admin
#COPY docs/public/index.html /usr/share/nginx/html/index.html


CMD ["nginx", "-g", "daemon off;"]
