import {ChangeDetectorRef, Component, DestroyRef, OnInit, ViewChild, inject} from '@angular/core';
import {ActivatedRoute, Router} from '@angular/router';
import {FieldDefinition} from '../../models/field-definition';
import {ApiService} from '../../services/api.service';
import {DataListService} from '../../services/data-list.service';
import {MetadataService} from '../../services/metadata.service';
import {Metadata} from '../../models/metadata';
import {DynamicSearchFormComponent} from '../../generic.components/dynamic-form/dynamic-search-form.component';
import {catchError, map} from 'rxjs/operators';
import {Observable, of} from 'rxjs';
import {FieldDefinitionService} from '../../services/field-definition.service';
import { SideBarComponent } from '../sidebar/sidebar.component';
import { HomepageTopBar } from '../homepage-topbar/homepage-topbar.component';
import { TableModule } from 'primeng/table';
import { PrimeTemplate } from 'primeng/api';
import { AsyncPipe } from '@angular/common';
import {takeUntilDestroyed} from '@angular/core/rxjs-interop';
import {applySearchFormValues, buildSearchFieldDefinitions, isPassivationSearchField} from './search-filters.util';
import {DocumentService} from '../../services/document.service';
import Keycloak, {KeycloakTokenParsed} from 'keycloak-js';

@Component({
    standalone: true,
    templateUrl: './form-generation-list.component.html',
    imports: [SideBarComponent, HomepageTopBar, DynamicSearchFormComponent, TableModule, PrimeTemplate, AsyncPipe],
    styles: [`
        .list-image-preview {
            width: 150px;
            height: 150px;
            object-fit: cover;
            border-radius: 4px;
            border: 1px solid #d9d9d9;
            background-color: #f7f7f7;
        }

        .list-image-empty {
            color: #8a8a8a;
        }

        .list-media-preview {
            width: 56px;
            height: 56px;
            object-fit: cover;
            border-radius: 6px;
            border: 1px solid #ddd;
            background: #f8f9fa;
        }

        .list-media-icon-box {
            width: 56px;
            height: 56px;
            display: flex;
            align-items: center;
            justify-content: center;
            border-radius: 6px;
            border: 1px solid #ddd;
            background: #f8f9fa;
            color: #6c757d;
            font-size: 24px;
        }
    `]
})
export class FormGenerationListComponent implements OnInit {
    private static readonly LIST_TEXT_MAX_LENGTH = 100;
    private static readonly DEFAULT_TABLE_ROWS = 10;
    fieldDefinitionsList: FieldDefinition[] = [];
    fieldDefinitionsSearch: FieldDefinition[] = [];

    metadataName: string;
    model: any[] = [];
    tableFirst = 0;
    tableRows = FormGenerationListComponent.DEFAULT_TABLE_ROWS;
    metadata: Metadata;
    readonly canEditContent: boolean;
    readonly canViewContent: boolean;
    private metadataReady = false;
    private definitionsReady = false;
    private pendingLazyEvent: any | null = null;
    private initialLoadTriggered = false;
    private debugEnabled = false;

    @ViewChild(DynamicSearchFormComponent)
    set searchForm(component: DynamicSearchFormComponent | undefined) {
        this._searchForm = component;
        this.syncSearchFormState();
    }

    get searchForm(): DynamicSearchFormComponent | undefined {
        return this._searchForm;
    }

    private readonly destroyRef = inject(DestroyRef);
    private readonly keycloak = inject(Keycloak);
    private _searchForm?: DynamicSearchFormComponent;
    private rangeAutofillBound = false;
    private lastAutoGeneratedRangeMax = new Map<string, string>();
    private restoredSearchValues: Record<string, unknown> | null = null;
    private restoredFormValues: Record<string, unknown> | null = null;
    private activeSearchValues: Record<string, unknown> = {};

    constructor(
        protected router: Router,
        private route: ActivatedRoute,
        public apiService: ApiService,
        private dataListService: DataListService,
        private metadataService: MetadataService,
        private fieldDefintionService: FieldDefinitionService,
        public documentService: DocumentService,
        private cdr: ChangeDetectorRef) {
        const userRoles = this.getUserRoles();
        this.canEditContent = this.hasAnyRole(userRoles, ['admin', 'contents_edit']);
        this.canViewContent = this.canEditContent || this.hasAnyRole(userRoles, ['contents_view']);
    }

    private hasAnyRole(userRoles: string[], requiredRoles: string[]): boolean {
        return requiredRoles.some(requiredRole => userRoles.includes(requiredRole));
    }

    private getUserRoles(): string[] {
        const parsed = this.keycloak.tokenParsed as KeycloakTokenParsed & {
            realm_access?: { roles?: string[] };
            resource_access?: Record<string, { roles?: string[] }>;
        };
        const realmRoles = parsed?.realm_access?.roles ?? [];
        const resourceRoles = Object.values(parsed?.resource_access ?? {})
            .flatMap(resource => resource.roles ?? []);

        return [...realmRoles, ...resourceRoles]
            .filter((role): role is string => typeof role === 'string')
            .map(role => role.toLowerCase());
    }

    public getImagePreviewUrl(value: unknown): string {
        const imageRef = this.extractImageUuid(value);
        if (!imageRef) {
            return '';
        }

        if (this.isLikelyImageUrl(imageRef)) {
            return imageRef;
        }

        return this.documentService.downloadPath(imageRef);
    }

    public hasImagePreview(value: unknown): boolean {
        return this.extractImageUuid(value) !== '';
    }

    private extractImageUuid(value: unknown): string {
        if (typeof value === 'string') {
            const trimmed = value.trim();
            if (!trimmed) {
                return '';
            }

            if ((trimmed.startsWith('{') && trimmed.endsWith('}')) || (trimmed.startsWith('[') && trimmed.endsWith(']'))) {
                try {
                    return this.extractImageUuid(JSON.parse(trimmed));
                } catch {
                    return trimmed;
                }
            }

            return trimmed;
        }

        if (Array.isArray(value)) {
            for (const item of value) {
                const extracted = this.extractImageUuid(item);
                if (extracted) {
                    return extracted;
                }
            }
            return '';
        }

        if (value && typeof value === 'object') {
            const candidate = value as {
                uuid?: unknown;
                id?: unknown;
                _id?: unknown;
                document_uuid?: unknown;
                value?: unknown;
                table_key?: unknown;
                url?: unknown;
                path?: unknown;
            };

            const keys: Array<unknown> = [
                candidate.uuid,
                candidate.document_uuid,
                candidate.id,
                candidate._id,
                candidate.url,
                candidate.path,
                candidate.value,
                candidate.table_key
            ];

            for (const keyValue of keys) {
                const extracted = this.extractImageUuid(keyValue);
                if (extracted) {
                    return extracted;
                }
            }
        }

        return '';
    }

    private isLikelyImageUrl(value: string): boolean {
        return /^https?:\/\//i.test(value) || value.startsWith('/') || value.startsWith('data:image/');
    }

    private applySearchDefaults() {
        for (const field of this.fieldDefinitionsSearch) {
            if (isPassivationSearchField(field)) {
                if (field.value == null) {
                    field.value = true;
                }
                if (field.name && this.searchForm?.searchForm?.get(field.name) && this.searchForm.searchForm.get(field.name)?.value == null) {
                    this.searchForm.searchForm.get(field.name)?.setValue(true, {emitEvent: false});
                }
            }
        }
    }

    private syncSearchFormState() {
        this.debug('syncSearchFormState:start', {
            hasForm: !!this.searchForm?.searchForm,
            searchFields: this.fieldDefinitionsSearch.length,
            restoredKeys: this.restoredSearchValues ? Object.keys(this.restoredSearchValues).length : 0,
            activeKeys: Object.keys(this.activeSearchValues).length
        });
        this.applySearchDefaults();
        this.restoreSearchFormState();
        this.bindRangeAutofill();
        this.debug('syncSearchFormState:done', {
            formValue: this.searchForm?.value,
            activeSearchValues: this.activeSearchValues
        });
    }

    private get stateStorageKey(): string {
        return `datalist:list-state:${this.metadataName}`;
    }

    private loadListState() {
        if (!this.metadataName) {
            return;
        }

        try {
            const rawState = localStorage.getItem(this.stateStorageKey);
            if (!rawState) {
                return;
            }

            const parsedState = JSON.parse(rawState) as {
                first?: unknown;
                rows?: unknown;
                searchValues?: Record<string, unknown>;
                formValues?: Record<string, unknown>;
            };

            const restoredFirst = Number(parsedState.first);
            const restoredRows = Number(parsedState.rows);

            this.tableFirst = Number.isFinite(restoredFirst) && restoredFirst >= 0 ? restoredFirst : 0;
            this.tableRows = Number.isFinite(restoredRows) && restoredRows > 0
                ? restoredRows
                : FormGenerationListComponent.DEFAULT_TABLE_ROWS;
            this.restoredSearchValues = parsedState.searchValues ?? null;
            this.restoredFormValues = parsedState.formValues ?? null;
            this.activeSearchValues = this.restoredSearchValues ? {...this.restoredSearchValues} : {};

            this.apiService._start = this.tableFirst;
            this.apiService._limit = this.tableRows;
            this.debug('loadListState:loaded', {
                tableFirst: this.tableFirst,
                tableRows: this.tableRows,
                restoredSearchValues: this.restoredSearchValues,
                activeSearchValues: this.activeSearchValues
            });
        } catch {
            this.tableFirst = 0;
            this.tableRows = FormGenerationListComponent.DEFAULT_TABLE_ROWS;
            this.restoredSearchValues = null;
            this.restoredFormValues = null;
            this.activeSearchValues = {};
            this.debug('loadListState:error-reset');
        }
    }

    private persistListState() {
        if (!this.metadataName) {
            return;
        }

        const payload = {
            first: this.tableFirst,
            rows: this.tableRows,
            searchValues: this.activeSearchValues,
            formValues: this.buildSearchSnapshotFromForm()
        };

        try {
            localStorage.setItem(this.stateStorageKey, JSON.stringify(payload));
            this.debug('persistListState', payload);
        } catch {
            // Ignore storage failures (quota/private mode) and continue without persistence.
            this.debug('persistListState:failed');
        }
    }

    private clearListStateCache() {
        if (!this.metadataName) {
            return;
        }

        this.restoredSearchValues = null;
        this.restoredFormValues = null;

        try {
            localStorage.removeItem(this.stateStorageKey);
            this.debug('clearListStateCache:done', {key: this.stateStorageKey});
        } catch {
            this.debug('clearListStateCache:failed');
        }
    }

    private restoreSearchFormState() {
        const sourceValues = this.restoredFormValues ?? this.restoredSearchValues ?? this.activeSearchValues;
        if (!sourceValues || this.fieldDefinitionsSearch.length === 0) {
            return;
        }

        const normalizedValues: Record<string, unknown> = {};
        for (const field of this.fieldDefinitionsSearch) {
            const fieldName = field.name;
            if (!fieldName || !Object.prototype.hasOwnProperty.call(sourceValues, fieldName)) {
                continue;
            }

            const restoredValue = this.normalizeRestoredSearchValue(field, sourceValues[fieldName]);
            field.value = restoredValue;
            normalizedValues[fieldName] = restoredValue;
        }

        if (this.searchForm?.searchForm && Object.keys(normalizedValues).length > 0) {
            this.searchForm.searchForm.patchValue(normalizedValues, {emitEvent: false});
        }

        this.activeSearchValues = {
            ...this.activeSearchValues,
            ...normalizedValues
        };
    }

    private buildSearchSnapshotFromForm(): Record<string, unknown> {
        if (this.searchForm?.value) {
            return {...(this.searchForm.value as Record<string, unknown>)};
        }

        const fallback: Record<string, unknown> = {};
        for (const field of this.fieldDefinitionsSearch) {
            if (!field.name) {
                continue;
            }
            fallback[field.name] = field.value;
        }
        return fallback;
    }

    private hasMeaningfulSearchValue(values: Record<string, unknown>): boolean {
        for (const field of this.fieldDefinitionsSearch) {
            if (!field.name || !Object.prototype.hasOwnProperty.call(values, field.name)) {
                continue;
            }

            const value = values[field.name];
            if (isPassivationSearchField(field)) {
                if (value === false) {
                    return true;
                }
                continue;
            }

            if (value !== null && value !== undefined && value !== '') {
                return true;
            }
        }

        return false;
    }

    private syncActiveSearchValuesFromForm() {
        const snapshot = this.buildSearchSnapshotFromForm();
        const currentHasMeaningfulValues = this.hasMeaningfulSearchValue(this.activeSearchValues);
        const snapshotHasMeaningfulValues = this.hasMeaningfulSearchValue(snapshot);

        if (snapshotHasMeaningfulValues || !currentHasMeaningfulValues) {
            this.activeSearchValues = snapshot;
        }
        this.debug('syncActiveSearchValuesFromForm', {
            formValue: this.searchForm?.value,
            activeSearchValues: this.activeSearchValues
        });
    }

    private processPendingLazyEventIfReady() {
        if (!this.pendingLazyEvent || !this.metadataReady || !this.definitionsReady) {
            return;
        }

        const pendingEvent = this.pendingLazyEvent;
        this.pendingLazyEvent = null;
        this.debug('processPendingLazyEventIfReady:run', {
            pendingEvent,
            metadataReady: this.metadataReady,
            definitionsReady: this.definitionsReady
        });
        this.lazyLoad(pendingEvent);
    }

    private triggerInitialLoadIfReady(datatable?: any) {
        if (this.initialLoadTriggered || !this.metadataReady || !this.definitionsReady) {
            return;
        }

        this.initialLoadTriggered = true;
        this.debug('triggerInitialLoadIfReady', {
            tableFirst: this.tableFirst,
            tableRows: this.tableRows,
            metadataReady: this.metadataReady,
            definitionsReady: this.definitionsReady,
            hasPendingLazyEvent: !!this.pendingLazyEvent,
            activeSearchValues: this.activeSearchValues
        });
        if (this.pendingLazyEvent) {
            this.processPendingLazyEventIfReady();
            return;
        }

        this.apiService._start = this.tableFirst;
        this.apiService._limit = this.tableRows;
        this.loaddata(datatable);
    }

    private debug(message: string, payload?: unknown) {
        if (!this.debugEnabled) {
            return;
        }

        if (payload !== undefined) {
            console.log('[FormGenerationList]', message, payload);
            return;
        }

        console.log('[FormGenerationList]', message);
    }

    private normalizeRestoredSearchValue(field: FieldDefinition, value: unknown): unknown {
        if (value == null) {
            return value;
        }

        if ((field.type === 'date' || field.type === 'datetime' || field.type === 'time') && typeof value === 'string') {
            const parsed = new Date(value);
            if (!Number.isNaN(parsed.getTime())) {
                return parsed;
            }
        }

        return value;
    }

    private bindRangeAutofill() {
        if (this.rangeAutofillBound || !this.searchForm?.searchForm || this.fieldDefinitionsSearch.length === 0) {
            return;
        }

        this.rangeAutofillBound = true;
        for (const field of this.fieldDefinitionsSearch) {
            if (!field.name?.endsWith('__min') || field.type !== 'date') {
                continue;
            }

            const maxFieldName = field.name.replace(/__min$/, '__max');
            const minControl = this.searchForm.searchForm.get(field.name);
            const maxControl = this.searchForm.searchForm.get(maxFieldName);
            if (!minControl || !maxControl) {
                continue;
            }

            minControl.valueChanges
                .pipe(takeUntilDestroyed(this.destroyRef))
                .subscribe(value => {
                    const minDate = this.toComparableDate(value);
                    const lastAutoValue = this.lastAutoGeneratedRangeMax.get(maxFieldName) ?? '';
                    const currentMaxValue = maxControl.value;
                    const currentMaxSerialized = this.toLocalDateString(currentMaxValue);

                    if (!minDate) {
                        if (currentMaxSerialized && currentMaxSerialized === lastAutoValue) {
                            maxControl.setValue(null, {emitEvent: false});
                            this.updateSearchFieldValue(maxFieldName, undefined);
                            this.lastAutoGeneratedRangeMax.delete(maxFieldName);
                        }
                        return;
                    }

                    const endOfMonth = new Date(minDate.getFullYear(), minDate.getMonth() + 1, 0);
                    const nextAutoValue = this.toLocalDateString(endOfMonth);

                    if (currentMaxSerialized && lastAutoValue && currentMaxSerialized !== lastAutoValue) {
                        return;
                    }

                    const autoFilledDate = new Date(endOfMonth.getTime());
                    maxControl.setValue(autoFilledDate, {emitEvent: false});
                    this.updateSearchFieldValue(maxFieldName, autoFilledDate);
                    this.lastAutoGeneratedRangeMax.set(maxFieldName, nextAutoValue);
                });
        }
    }

    private updateSearchFieldValue(fieldName: string, value: unknown) {
        const field = this.fieldDefinitionsSearch.find(candidate => candidate.name === fieldName);
        if (field) {
            field.value = value;
        }
    }

    private toComparableDate(value: unknown): Date | null {
        if (value instanceof Date) {
            return Number.isNaN(value.getTime()) ? null : value;
        }

        if (typeof value !== 'string' || value.trim() === '') {
            return null;
        }

        const parsed = new Date(value);
        return Number.isNaN(parsed.getTime()) ? null : parsed;
    }

    private toLocalDateString(value: unknown): string {
        const date = this.toComparableDate(value);
        if (!date) {
            return '';
        }

        const year = date.getFullYear();
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const day = String(date.getDate()).padStart(2, '0');
        return `${year}-${month}-${day}`;
    }

    private readonly rawTableKeyField = '__rawTableKeyValue';

    private getElementPropertyName(element: Record<string, unknown>, fieldName: string): string | null {
        if (!element || !fieldName) {
            return null;
        }

        if (Object.prototype.hasOwnProperty.call(element, fieldName)) {
            return fieldName;
        }

        const lowerFieldName = fieldName.toLowerCase();
        const matchedKey = Object.keys(element).find(key => key.toLowerCase() === lowerFieldName);
        return matchedKey ?? null;
    }

    private getElementPropertyValue(element: Record<string, unknown>, fieldName: string): unknown {
        const propertyName = this.getElementPropertyName(element, fieldName);
        if (!propertyName) {
            return null;
        }
        return element[propertyName];
    }

    private getTableKeyFieldName(): string {
        const fromMetadata = this.metadata?.table_key;
        if (fromMetadata) {
            return fromMetadata;
        }
        return '';
    }

    private resolveTableKeyValue(rawValue: unknown): string {
        if (rawValue == null) {
            return '';
        }

        if (typeof rawValue !== 'object') {
            return String(rawValue);
        }

        return '';
    }

    private formatFieldValue(fullValue: unknown, fieldDefinition: FieldDefinition): unknown {
        if (fullValue == null || fullValue === '') {
            return '';
        }

        if (fieldDefinition.type === 'image') {
            return this.extractImageUuid(fullValue);
        }

        if (fieldDefinition.type === 'date') {
            return this.formatDateValue(fullValue);
        }

        if (fieldDefinition.type === 'datetime') {
            return this.formatDateTimeValue(fullValue);
        }

        if (fieldDefinition.type === 'time') {
            return this.formatTimeValue(fullValue);
        }

        return fullValue;
    }

    private extractMediaMimeType(value: unknown): string {
        if (!value || typeof value !== 'object') {
            return '';
        }

        const candidate = value as Record<string, unknown>;
        const mimeType = candidate['mimetype'];
        return typeof mimeType === 'string' ? mimeType.toLowerCase() : '';
    }

    public getMediaPreviewUrl(value: unknown): string {
        const mediaRef = this.extractImageUuid(value);
        if (!mediaRef) {
            return '';
        }

        if (this.isLikelyImageUrl(mediaRef)) {
            return mediaRef;
        }

        return this.documentService.downloadPath(mediaRef);
    }

    public isMediaImage(value: unknown): boolean {
        const mimeType = this.extractMediaMimeType(value);
        if (mimeType) {
            return mimeType.startsWith('image/');
        }

        const mediaRef = this.extractImageUuid(value);
        return this.isLikelyImageUrl(mediaRef);
    }

    public mediaIconClass(value: unknown): string {
        const mimeType = this.extractMediaMimeType(value);
        if (!mimeType) {
            return 'fa fa-file-o';
        }

        if (mimeType.includes('pdf')) {
            return 'fa fa-file-pdf-o';
        }

        if (mimeType.includes('word') || mimeType.includes('msword')) {
            return 'fa fa-file-word-o';
        }

        if (mimeType.includes('excel') || mimeType.includes('spreadsheet')) {
            return 'fa fa-file-excel-o';
        }

        if (mimeType.includes('powerpoint') || mimeType.includes('presentation')) {
            return 'fa fa-file-powerpoint-o';
        }

        if (mimeType.includes('zip') || mimeType.includes('rar') || mimeType.includes('7z') || mimeType.includes('tar')) {
            return 'fa fa-file-archive-o';
        }

        if (mimeType.startsWith('text/') || mimeType.includes('json') || mimeType.includes('xml')) {
            return 'fa fa-file-text-o';
        }

        return 'fa fa-file-o';
    }

    public formatListCellValue(value: unknown, fieldDefinition: FieldDefinition): string {
        if (value == null) {
            return '';
        }

        const normalizedValue = typeof value === 'string' ? value : String(value);
        if (fieldDefinition.type !== 'textarea') {
            return normalizedValue;
        }

        if (normalizedValue.length <= FormGenerationListComponent.LIST_TEXT_MAX_LENGTH) {
            return normalizedValue;
        }

        return `${normalizedValue.slice(0, FormGenerationListComponent.LIST_TEXT_MAX_LENGTH)}...`;
    }

    public getRowFieldValueObservable(rowData: Record<string, unknown>, fieldDefinition: FieldDefinition): Observable<unknown> {
        const fieldName = fieldDefinition.name;
        if (!fieldName) {
            return of('');
        }

        return (rowData[fieldName] as Observable<unknown>) ?? of('');
    }

    private toValidDate(value: unknown): Date | null {
        if (value instanceof Date) {
            return Number.isNaN(value.getTime()) ? null : value;
        }

        if (typeof value !== 'string' || value.trim() === '') {
            return null;
        }

        const parsed = new Date(value);
        return Number.isNaN(parsed.getTime()) ? null : parsed;
    }

    private formatDateValue(value: unknown): string {
        if (typeof value === 'string') {
            const match = value.trim().match(/^(\d{4})-(\d{2})-(\d{2})$/);
            if (match) {
                return `${match[3]}/${match[2]}/${match[1]}`;
            }
        }

        const parsed = this.toValidDate(value);
        if (!parsed) {
            return String(value);
        }

        return new Intl.DateTimeFormat('it-IT', {
            year: 'numeric',
            month: '2-digit',
            day: '2-digit'
        }).format(parsed);
    }

    private formatDateTimeValue(value: unknown): string {
        const parsed = this.toValidDate(value);
        if (!parsed) {
            return String(value);
        }

        return new Intl.DateTimeFormat('it-IT', {
            year: 'numeric',
            month: '2-digit',
            day: '2-digit',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit'
        }).format(parsed);
    }

    private formatTimeValue(value: unknown): string {
        if (typeof value === 'string') {
            const match = value.trim().match(/^(\d{2}):(\d{2})(?::(\d{2}))?$/);
            if (match) {
                return `${match[1]}:${match[2]}:${match[3] ?? '00'}`;
            }
        }

        const parsed = this.toValidDate(value);
        if (!parsed) {
            return String(value);
        }

        return new Intl.DateTimeFormat('it-IT', {
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
            hour12: false
        }).format(parsed);
    }


    private datoAsObservableOfValue(rowData: any, fieldDefinition: FieldDefinition): Observable<any> {
        const fieldName = fieldDefinition.name;
        if (!fieldName) {
            return of('');
        }

        const fullValue = this.getElementPropertyValue(rowData as Record<string, unknown>, fieldName);

        if (fieldDefinition.type === 'image') {
            const imageRef = this.extractImageUuid(fullValue);
            if (imageRef) {
                return of(imageRef);
            }

            const tableKey = this.getTableKey(rowData);
            if (!tableKey) {
                return of('');
            }

            return this.documentService.getDocumentsByTable(this.metadataName, tableKey).pipe(
                map(docs => {
                    const imageDoc = (docs ?? []).find(doc => doc?.uuid);
                    return imageDoc?.uuid ?? '';
                }),
                catchError(() => of(''))
            );
        }

        if (fieldDefinition.type === 'media') {
            const mediaRef = this.extractImageUuid(fullValue);
            if (!mediaRef) {
                return of('');
            }

            if (this.isLikelyImageUrl(mediaRef)) {
                return of({uuid: mediaRef, mimetype: 'image/*'});
            }

            return this.documentService.find(mediaRef).pipe(
                map(document => ({
                    uuid: document?.uuid ?? mediaRef,
                    mimetype: document?.mimetype ?? '',
                    original_name: document?.original_name ?? ''
                })),
                catchError(() => of({uuid: mediaRef, mimetype: ''}))
            );
        }

        if (fullValue == null || fullValue === '') {
            return of('');
        }

        if (fieldDefinition.type === 'join') {
            const labelField = this.fieldDefintionService.fetchFirstLabel(fieldDefinition);
            const fullValueObject = fullValue as Record<string, unknown>;
            const joinValue = typeof fullValue === 'object' && fullValue != null && fieldDefinition.join_table_key
                ? fullValueObject[fieldDefinition.join_table_key]
                : fullValue;

            if (joinValue == null || joinValue === '') {
                return of('');
            }

            return this.apiService.fetchObject(fieldDefinition.join_table_name, String(joinValue), fieldDefinition.join_table_select_fields)
                .pipe(
                    map(join => {
                        return join[labelField];
                    })
                );
        } else if (fieldDefinition.type === 'multijoin') {
            const labelField = this.fieldDefintionService.fetchFirstLabel(fieldDefinition);
            const ids = Array.isArray(fullValue)
                ? fullValue.map(value => String(value).trim()).filter(Boolean)
                : String(fullValue)
                    .split(',')
                    .map(value => value.trim())
                    .filter(Boolean);

            if (ids.length === 0) {
                return of('');
            }

            const selectFields = `${fieldDefinition.join_table_select_fields},${fieldDefinition.join_table_key}`;
            return this.apiService.fetchObjectsByKeys(
                fieldDefinition.join_table_name,
                fieldDefinition.join_table_key,
                ids,
                selectFields
            ).pipe(
                map(items => items
                    .map(item => item?.[labelField])
                    .filter(value => value != null && value !== '')
                    .join(', '))
            );
        } else {
            return of(this.formatFieldValue(fullValue, fieldDefinition));
        }

    }

    ngOnInit() {
        this.metadataName = this.route.snapshot.params['name'];
        this.debugEnabled = this.route.snapshot.queryParamMap.get('debugList') === '1'
            || localStorage.getItem('datalistDebug') === '1';
        this.debug('ngOnInit:start', {
            metadataName: this.metadataName,
            debugEnabled: this.debugEnabled
        });
        this.metadataService.buildSearch();
        this.loadListState();
        this.metadataService._start = this.tableFirst;
        this.metadataService._limit = this.tableRows;
        this.metadataService.search.table_name = this.metadataName;
        this.metadataService.getList().subscribe(
            metadata => {
                if (metadata != null && metadata.length > 0) {
                    this.metadata = metadata[0];
                    this.metadataReady = !!this.metadata?.table_key;
                    this.debug('metadataService:getList:ready', {
                        metadataReady: this.metadataReady,
                        tableKey: this.metadata?.table_key
                    });
                    this.processPendingLazyEventIfReady();
                    this.triggerInitialLoadIfReady();
                }
            }
        );


        this.route.data
            .subscribe(
                (data: unknown) => {
                    const resolved = (data as { fieldDefinitionValorized?: FieldDefinition[] })?.fieldDefinitionValorized;
                    this.fieldDefinitionsList = resolved ?? [];
                    this.fieldDefinitionsSearch = buildSearchFieldDefinitions(this.fieldDefinitionsList);
                    this.rangeAutofillBound = false;
                    this.syncSearchFormState();
                    this.syncActiveSearchValuesFromForm();
                    this.definitionsReady = true;
                    this.debug('route.data:definitionsReady', {
                        fieldDefinitionsList: this.fieldDefinitionsList.length,
                        fieldDefinitionsSearch: this.fieldDefinitionsSearch.length,
                        activeSearchValues: this.activeSearchValues
                    });
                    this.processPendingLazyEventIfReady();
                    this.triggerInitialLoadIfReady();
                }
            );
    }

    public newForm() {
        this.persistListState();
        if (this.fieldDefinitionsList) {
            this.router.navigate(['datalist/new', this.metadataName]);
        }
    }

    public newMassiveForm() {
        this.persistListState();
        this.router.navigate(['datalist/new', this.metadataName], {
            queryParams: {
                massive: 'true'
            }
        });
    }

    public openCalendar() {
        this.persistListState();
        this.router.navigate(['calendar/list', this.metadataName]);
    }

    public edit(rowData: any) {
        this.persistListState();
        this.router.navigate(['datalist/edit', this.metadataName, this.getTableKey(rowData)]);
    }

    public view(rowData: any) {
        this.persistListState();
        this.router.navigate(['datalist/view', this.metadataName, this.getTableKey(rowData)]);
    }

    public clone(rowData: any) {
        this.persistListState();
        this.router.navigate(['datalist/new', this.metadataName], {
            queryParams: {
                clone_uuid: this.getTableKey(rowData)
            }
        });
    }

    public loaddata(datatable?: any) {
        this.debug('loaddata:start', {
            tableFirst: this.tableFirst,
            tableRows: this.tableRows,
            apiStart: this.apiService._start,
            apiLimit: this.apiService._limit,
            activeSearchValues: this.activeSearchValues
        });
        this.preLoaddata();
        const tableKeyFieldName = this.getTableKeyFieldName();

        // if (this.searchForm && this.searchForm.value) {
        //     const objToSearch = JSON.parse(JSON.stringify(this.searchForm.value));
        //     for (const k in objToSearch) {
        //         if (objToSearch.hasOwnProperty(k)) {
        //             for (const field of this.fieldDefinitionsSearch) {
        //                 if (field.name === k) {
        //                     field.value = objToSearch[field.name];
        //                 }
        //             }
        //         }
        //     }
        // }
        // valorizza valiri di ricerca con le fileddefinitions
        this.preSearch();

        this.apiService._limit = this.tableRows;
        this.apiService.getList(this.metadataName, this.fieldDefinitionsSearch).subscribe(
            model => {
                this.debug('loaddata:response', {
                    modelLength: model.length,
                    listSize: this.apiService.listSize,
                    tableFirst: this.tableFirst,
                    tableRows: this.tableRows
                });
                const fallbackStart = this.apiService.listSize > 0
                    ? Math.max(0, Math.floor((this.apiService.listSize - 1) / this.tableRows) * this.tableRows)
                    : 0;
                if (model.length === 0 && this.tableFirst > 0 && fallbackStart !== this.tableFirst) {
                    this.tableFirst = fallbackStart;
                    this.apiService._start = fallbackStart;
                    if (datatable) {
                        datatable.first = fallbackStart;
                    }
                    this.persistListState();
                    this.loaddata(datatable);
                    return;
                }

                for (let element of model) {
                    if (element != null) {
                        element[this.rawTableKeyField] = tableKeyFieldName
                            ? this.getElementPropertyValue(element as Record<string, unknown>, tableKeyFieldName)
                            : null;

                        for (const definition_1 of this.fieldDefinitionsList) {
                            if (!definition_1.name) {
                                continue;
                            }
                            definition_1.is_edit = true;
                            const existingPropertyName = this.getElementPropertyName(element as Record<string, unknown>, definition_1.name);
                            //cerco la field defintion
                            if (existingPropertyName) {
                                // Se è la mia devo scrivere il dato come observable
                                element[definition_1.name] = this.datoAsObservableOfValue(element, definition_1);
                            }
                        }
                    }
                }
                this.model = model;
                this.cdr.detectChanges();
            }
        );
    }

    public preLoaddata() {
    }

    public lazyLoad(
        event: any, datatable?: any) {

        this.debug('lazyLoad:event', {
            event,
            metadataReady: this.metadataReady,
            definitionsReady: this.definitionsReady,
            activeSearchValues: this.activeSearchValues
        });

        if (!this.metadataReady || !this.definitionsReady) {
            this.pendingLazyEvent = event;
            this.debug('lazyLoad:queued', {pendingLazyEvent: this.pendingLazyEvent});
            return;
        }

        this.tableFirst = event.first ?? 0;
        this.apiService._start = this.tableFirst;
        this.tableRows = event.rows ?? this.tableRows;
        this.apiService._limit = this.tableRows;
        this.initialLoadTriggered = true;
        this.persistListState();
        this.loaddata(datatable);
    }

    public getTableKey(fieldDefinition: any): string {
        const tableKeyFieldName = this.getTableKeyFieldName();
        const rawValue = fieldDefinition?.[this.rawTableKeyField]
            ?? (tableKeyFieldName
                ? this.getElementPropertyValue(fieldDefinition as Record<string, unknown>, tableKeyFieldName)
                : null);
        return this.resolveTableKeyValue(rawValue);
    }

    public reload(datatable: any) {
        this.syncActiveSearchValuesFromForm();
        this.debug('reload', {
            activeSearchValues: this.activeSearchValues
        });
        this.tableFirst = 0;
        this.apiService._start = 0;
        this.apiService._limit = this.tableRows;
        this.initialLoadTriggered = true;
        if (datatable) {
            datatable.first = 0;
        }
        this.loaddata(datatable);
    }

    public onSearchEnter(event: Event, datatable: any) {
        event.preventDefault();
        this.reload(datatable);
    }

    public refresh(datatable: any) {
        this.clearMsgs();
        this.loaddata(datatable);
    }

    public reset(datatable: any) {
        const obj: Record<string, unknown> = {};
        if (this.searchForm && this.searchForm.value) {
            for (const k in this.searchForm.value) {
                if (this.searchForm.value.hasOwnProperty(k)) {
                    obj[k] = null;
                }
            }
            for (const field of this.fieldDefinitionsSearch) {
                if (field.name && isPassivationSearchField(field)) {
                    obj[field.name] = true;
                    field.value = true;
                }
            }
            this.searchForm.searchForm.setValue(obj);
        }
        this.activeSearchValues = {...obj};
        this.debug('reset', {
            activeSearchValues: this.activeSearchValues
        });
        this.tableFirst = 0;
        this.apiService._start = 0;
        this.apiService._limit = this.tableRows;
        this.initialLoadTriggered = true;
        this.clearListStateCache();
        if (datatable) {
            datatable.first = 0;
        }
        this.lastAutoGeneratedRangeMax.clear();
        this.loaddata(datatable);
    }

    public clearMsgs() {
        // this.msgs = [];
    }

    private clearSearchFieldValues() {
        for (const field of this.fieldDefinitionsSearch) {
            if (isPassivationSearchField(field)) {
                field.value = true;
                continue;
            }

            field.value = null;
        }
    }

    // ribalta le proprieta dal form di ricerca in alto, sulla fieldDefinitionsSearch
    private preSearch() {
        this.clearSearchFieldValues();
        applySearchFormValues(this.fieldDefinitionsSearch, this.activeSearchValues);
        this.debug('preSearch', {
            activeSearchValues: this.activeSearchValues,
            mappedSearchFields: this.fieldDefinitionsSearch
                .filter(field => field.search_field_name)
                .map(field => ({
                    name: field.name,
                    searchField: field.search_field_name,
                    value: field.value
                }))
                .filter(field => field.value != null && field.value !== '')
        });
        this.persistListState();
    }
}
