import {Component, DestroyRef, OnInit, ViewChild, inject} from '@angular/core';
import {ActivatedRoute, Router} from '@angular/router';
import {CalendarOptions, DatesSetArg, EventClickArg, EventInput} from '@fullcalendar/core';
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGridPlugin from '@fullcalendar/timegrid';
import {FullCalendarModule} from '@fullcalendar/angular';
import {ApiService} from '../../services/api.service';
import {MetadataService} from '../../services/metadata.service';
import {DataListService} from '../../services/data-list.service';
import {Metadata} from '../../models/metadata';
import {FieldDefinition} from '../../models/field-definition';
import {SideBarComponent} from '../sidebar/sidebar.component';
import {HomepageTopBar} from '../homepage-topbar/homepage-topbar.component';
import {DynamicFormComponent} from '../../generic.components/dynamic-form/dynamic-form.component';
import {DynamicSearchFormComponent} from '../../generic.components/dynamic-form/dynamic-search-form.component';
import {DialogModule} from 'primeng/dialog';
import {switchMap} from 'rxjs/operators';
import {takeUntilDestroyed} from '@angular/core/rxjs-interop';
import {applySearchFormValues, buildSearchFieldDefinitions} from './search-filters.util';

@Component({
    standalone: true,
    templateUrl: './form-generation-calendar.component.html',
    imports: [SideBarComponent, HomepageTopBar, FullCalendarModule, DynamicFormComponent, DynamicSearchFormComponent, DialogModule]
})
export class FormGenerationCalendarComponent implements OnInit {

    @ViewChild(DynamicSearchFormComponent)
    set searchForm(component: DynamicSearchFormComponent | undefined) {
        this._searchForm = component;
        this.bindRangeAutofill();
    }

    get searchForm(): DynamicSearchFormComponent | undefined {
        return this._searchForm;
    }

    metadataName: string;
    metadata: Metadata;
    errorMessage = '';

    fieldDefinitionsSearch: FieldDefinition[] = [];

    detailVisible = false;
    detailFields: FieldDefinition[] = [];
    detailUuid: string | null = null;

    // range attivo usato per il reload
    private currentRangeStart: Date | null = null;
    private currentRangeEnd: Date | null = null;
    private readonly destroyRef = inject(DestroyRef);
    private _searchForm?: DynamicSearchFormComponent;
    private rangeAutofillBound = false;
    private lastAutoGeneratedRangeMax = new Map<string, string>();

    calendarOptions: CalendarOptions = {
        plugins: [dayGridPlugin, timeGridPlugin],
        initialView: 'dayGridMonth',
        headerToolbar: {
            left: 'prev,next today',
            center: 'title',
            right: 'dayGridMonth,timeGridWeek'
        },
        events: [],
        datesSet: (arg: DatesSetArg) => this.onDatesSet(arg),
        eventClick: (arg: EventClickArg) => this.onEventClick(arg)
    };

    constructor(
        private route: ActivatedRoute,
        private router: Router,
        private apiService: ApiService,
        private metadataService: MetadataService,
        private dataListService: DataListService
    ) {}

    ngOnInit() {
        this.metadataName = this.route.snapshot.params['name'];
        this.metadataService.buildSearch();
        this.metadataService._start = 0;
        this.metadataService._limit = 1000;
        this.metadataService.search.table_name = this.metadataName;
        this.metadataService.getList().subscribe(metadataList => {
            if (metadataList && metadataList.length > 0) {
                this.metadata = metadataList[0];
                this.loadSearchFields();
            }
        });
    }

    private loadSearchFields() {
        this.dataListService.getFieldDefinitionList(this.metadataName).subscribe(fields => {
            this.fieldDefinitionsSearch = buildSearchFieldDefinitions(fields)
                .sort((a, b) => (a.order_num ?? 0) - (b.order_num ?? 0));
            this.rangeAutofillBound = false;
            this.bindRangeAutofill();
        });
    }

    private bindRangeAutofill() {
        if (this.rangeAutofillBound || !this.searchForm?.searchForm || this.fieldDefinitionsSearch.length === 0) {
            return;
        }

        this.rangeAutofillBound = true;
        for (const field of this.fieldDefinitionsSearch) {
            if (!field.name?.endsWith('__min') || field.type !== 'date') {
                continue;
            }

            const maxFieldName = field.name.replace(/__min$/, '__max');
            const minControl = this.searchForm.searchForm.get(field.name);
            const maxControl = this.searchForm.searchForm.get(maxFieldName);
            if (!minControl || !maxControl) {
                continue;
            }

            minControl.valueChanges
                .pipe(takeUntilDestroyed(this.destroyRef))
                .subscribe(value => {
                    const minDate = this.toComparableDate(value);
                    const lastAutoValue = this.lastAutoGeneratedRangeMax.get(maxFieldName) ?? '';
                    const currentMaxValue = maxControl.value;
                    const currentMaxSerialized = this.toLocalDateString(currentMaxValue);

                    if (!minDate) {
                        if (currentMaxSerialized && currentMaxSerialized === lastAutoValue) {
                            maxControl.setValue(null, {emitEvent: false});
                            this.updateSearchFieldValue(maxFieldName, undefined);
                            this.lastAutoGeneratedRangeMax.delete(maxFieldName);
                        }
                        return;
                    }

                    const endOfMonth = new Date(minDate.getFullYear(), minDate.getMonth() + 1, 0);
                    const nextAutoValue = this.toLocalDateString(endOfMonth);

                    if (currentMaxSerialized && lastAutoValue && currentMaxSerialized !== lastAutoValue) {
                        return;
                    }

                    const autoFilledDate = new Date(endOfMonth.getTime());
                    maxControl.setValue(autoFilledDate, {emitEvent: false});
                    this.updateSearchFieldValue(maxFieldName, autoFilledDate);
                    this.lastAutoGeneratedRangeMax.set(maxFieldName, nextAutoValue);
                });
        }
    }

    private updateSearchFieldValue(fieldName: string, value: unknown) {
        const field = this.fieldDefinitionsSearch.find(candidate => candidate.name === fieldName);
        if (field) {
            field.value = value;
        }
    }

    private mergeCalendarFilters(filters: FieldDefinition[]): FieldDefinition[] {
        const merged = new Map<string, FieldDefinition>();

        for (const filter of filters) {
            const key = filter.search_field_name;
            if (!key) {
                continue;
            }

            const existing = merged.get(key);
            if (!existing) {
                merged.set(key, filter);
                continue;
            }

            const nextValue = this.pickMergedFilterValue(key, existing.value, filter.value);
            merged.set(key, {...existing, value: nextValue});
        }

        return Array.from(merged.values());
    }

    private pickMergedFilterValue(searchFieldName: string, left: unknown, right: unknown): unknown {
        const leftDate = this.toComparableDate(left);
        const rightDate = this.toComparableDate(right);

        if (!leftDate || !rightDate) {
            return right ?? left;
        }

        if (searchFieldName.endsWith('_gte') || searchFieldName.endsWith('_gt')) {
            return leftDate >= rightDate ? left : right;
        }

        if (searchFieldName.endsWith('_lte') || searchFieldName.endsWith('_lt')) {
            return leftDate <= rightDate ? left : right;
        }

        return right;
    }

    private toComparableDate(value: unknown): Date | null {
        if (value instanceof Date) {
            return Number.isNaN(value.getTime()) ? null : value;
        }

        if (typeof value !== 'string' || value.trim() === '') {
            return null;
        }

        const parsed = new Date(value);
        return Number.isNaN(parsed.getTime()) ? null : parsed;
    }

    private validateSearchRanges(filters: FieldDefinition[]): boolean {
        const rangePairs = new Map<string, {min?: unknown; max?: unknown; label: string}>();

        for (const filter of filters) {
            const fieldName = filter.name ?? '';
            if (!fieldName.endsWith('__min') && !fieldName.endsWith('__max')) {
                continue;
            }

            const baseName = fieldName.replace(/__(min|max)$/, '');
            const existing = rangePairs.get(baseName) ?? {
                label: (filter.label || baseName).replace(/ (min|max)$/i, '')
            };

            if (fieldName.endsWith('__min')) {
                existing.min = filter.value;
            } else {
                existing.max = filter.value;
            }

            rangePairs.set(baseName, existing);
        }

        for (const [, pair] of rangePairs) {
            const minDate = this.toComparableDate(pair.min);
            const maxDate = this.toComparableDate(pair.max);

            if (!minDate || !maxDate) {
                continue;
            }

            if (minDate.getTime() >= maxDate.getTime()) {
                this.errorMessage = `${pair.label} min must be earlier than ${pair.label} max.`;
                return false;
            }
        }

        this.errorMessage = '';
        return true;
    }

    public search() {
        if (this.currentRangeStart && this.currentRangeEnd) {
            this.loadEventsForRange(this.currentRangeStart, this.currentRangeEnd);
        }
    }

    public reset() {
        if (this.searchForm?.searchForm) {
            const empty: Record<string, unknown> = {};
            for (const k of Object.keys(this.searchForm.searchForm.value)) {
                empty[k] = null;
            }
            this.searchForm.searchForm.setValue(empty);
        }
        for (const f of this.fieldDefinitionsSearch) {
            f.value = undefined;
        }
        this.lastAutoGeneratedRangeMax.clear();
        this.errorMessage = '';
        this.search();
    }

    public newForm() {
        this.router.navigate(['datalist/new', this.metadataName]);
    }

    public newMassiveForm() {
        this.router.navigate(['datalist/new', this.metadataName], {
            queryParams: {
                massive: 'true'
            }
        });
    }

    public goToList() {
        this.router.navigate(['datalist/list', this.metadataName]);
    }

    public editDetail() {
        if (this.detailUuid) {
            this.router.navigate(['datalist/edit', this.metadataName, this.detailUuid]);
        }
    }

    private onEventClick(arg: EventClickArg) {
        const uuid = arg.event.extendedProps['uuid'] as string;
        if (!uuid) { return; }
        this.detailUuid = uuid;
        this.detailFields = [];
        this.dataListService.getFieldDefinitionList(this.metadataName).pipe(
            switchMap(fields => {
                return this.apiService.fetchObject(this.metadataName, uuid).pipe(
                    switchMap(element => {
                        for (const def of fields) {
                            def.is_edit = true;
                            if (def.name && Object.prototype.hasOwnProperty.call(element, def.name)) {
                                def.value = element[def.name];
                            } else if (def.name && Object.prototype.hasOwnProperty.call(element, def.name.toLowerCase())) {
                                def.value = element[def.name.toLowerCase()];
                            }
                            def.table_name = this.metadataName;
                            def.table_key_value = uuid;
                        }
                        fields.sort((a, b) => (a.order_num ?? 0) - (b.order_num ?? 0));
                        return [fields];
                    })
                );
            })
        ).subscribe(fields => {
            this.detailFields = fields;
            this.detailVisible = true;
        });
    }

    private onDatesSet(arg: DatesSetArg) {
        this.currentRangeStart = arg.start;
        this.currentRangeEnd = arg.end;
        if (!this.metadata) {
            setTimeout(() => this.onDatesSet(arg), 300);
            return;
        }
        this.loadEventsForRange(arg.start, arg.end);
    }

    private toLocalDateString(value: unknown): string {
        const date = this.toComparableDate(value);
        if (!date) {
            return '';
        }

        const year = date.getFullYear();
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const day = String(date.getDate()).padStart(2, '0');
        return `${year}-${month}-${day}`;
    }

    private loadEventsForRange(start: Date, end: Date) {
        const calendarField = this.metadata.calendar_field;
        const calendarLabel = this.metadata.calendar_label;
        const tableKey = this.metadata.table_key;

        // filtri range data
        const rangeFilters: FieldDefinition[] = [
            {search_field_name: `${calendarField}_gte`, value: this.toLocalDateString(start)} as FieldDefinition,
            {search_field_name: `${calendarField}_lte`, value: this.toLocalDateString(end)} as FieldDefinition
        ];

        // filtri dinamici dal form di ricerca
        applySearchFormValues(this.fieldDefinitionsSearch, this.searchForm?.value as Record<string, unknown> | undefined);
        const dynamicFilters = this.fieldDefinitionsSearch
            .filter(field => field.value != null && field.value !== '')
            .map(field => ({...field}) as FieldDefinition);

        if (!this.validateSearchRanges(dynamicFilters)) {
            return;
        }

        const allFilters = this.mergeCalendarFilters([...rangeFilters, ...dynamicFilters]);

        this.apiService._start = 0;
        this.apiService._limit = 1000;
        this.apiService.getList(this.metadataName, allFilters).subscribe(items => {
            const events: EventInput[] = items
                .filter((item: Record<string, unknown>) => item[calendarField])
                .map((item: Record<string, unknown>) => ({
                    title: (item[calendarLabel] ?? this.metadataName) as string,
                    start: item[calendarField] as string,
                    extendedProps: {uuid: item[tableKey]}
                }));
            this.calendarOptions = {...this.calendarOptions, events};
        });
    }
}


