FROM nginx:1.23.3-alpine-slim

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY dist/snello-admin/browser/ /usr/share/nginx/html/

CMD ["nginx", "-g", "daemon off;"]
