FROM nginx:1.14.1-alpine

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

## From ‘builder’ stage copy over the artifacts in dist folder to default nginx public folder
COPY dist /usr/share/nginx/html

COPY  docs/public/index.html /usr/share/nginx/html


CMD ["nginx", "-g", "daemon off;"]
